"""SemanticOSRegistry — the hand-authored semantic layer (Concepts / Boundaries / Journeys).

The Semantic OS answers the questions code cannot: *why does this exist*, *what invariant must
never break*, *why this design*, *why was the alternative rejected*, *which finding justifies it*.
Everything code CAN answer — imports, consumers, package, ownership, size, tests, reachability —
is GENERATED by ``src/governance/semantic_objects.py`` and is a **schema violation** if hand-written
here (see ``_FORBIDDEN_HAND_FIELDS`` + ``validate_no_derived_in_source``).

Five hand-authored record kinds, one generated:

============  ==============  ==============================================================
Kind          Id              Role
============  ==============  ==============================================================
Concept       ``CN-``         Stable meaning. REFERENCES miar / closure / ontology / book /
                              findings by validated foreign key; owns none of them.
Boundary      ``BD-``         An architectural seam, **not a file list**. Owner + member GLOBS
                              + consumers + the invariant it protects. Survives churn.
Journey       ``JN-``         An ordered semantic path across concepts. Machine twin of
                              ``docs/architecture/signal-flow.md``.
Contract      ``CT-``         First-class constraints (inputs/outputs/guarantees/
                              non_guarantees/tests). May be referenced from BD.contract_ids.
FileIdentity  dotted slug     Rename-stable ``semantic_id -> semantic_name -> physical_path``
                              for one module, plus a ``filename_semantic_status`` classification
                              (ALIGNED/HISTORICAL/MISLEADING/COMPATIBILITY/SPLIT/UNKNOWN). Tier 1/2
                              curated in YAML; Tier 3 machine-derived at seed time (path_slug).
                              Grants no rename authority — advisory naming only.
Object        ``OBJ:``        100% generated — see ``semantic_objects.py``. Never authored.
============  ==============  ==============================================================

Authority (CLAUDE.md §6.5): every record pins ``authority = "advisory"``. Concept ownership and
boundary membership grant *navigability*, never *production authority* — only demonstrated G001
improvement does. ``validate_record`` rejects ``"production"`` outright.

Ontology precedence (§6.6): a Concept may CITE ``FM-*`` / ``SEM-*`` / ``UNK-*`` ids but may never
carry a formula. ``configs/formulas/market_ontology.yaml`` remains authority #1 for meaning.

Design notes (reuse, don't reinvent — CLAUDE.md §3.1):
  - class shape, ``ValidationError``, ``validate_record`` / ``dump`` mirror
    ``src/governance/framework_registry.py``;
  - evidence validation reuses that module's ``_resolve`` + ±30-line symbol-drift window;
  - finding validation reuses its ``valid_finding_ids()`` (``### F-NNN`` block regex).

Append-discipline (§6.2 rule 4): retired records stay in the YAML marked ``SUPERSEDED`` /
``RETIRED`` with ``superseded_by`` set. Never delete a record.

Usage:
    reg = SemanticOSRegistry.load()
    errors = reg.validate_all()
    concept = reg.get("CN-001")
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Optional

from governance.framework_registry import ValidationError, valid_finding_ids

_ROOT = Path(__file__).resolve().parents[2]
_GOV = _ROOT / "docs" / "governance"
_SEMANTIC_DIR = _GOV / "semantic_os"

# ── external authorities (FK targets) — all TRACKED by git as of CH-semantic-os-v2 ──────────
_ONTOLOGY = _ROOT / "configs" / "formulas" / "market_ontology.yaml"
_MIAR = _GOV / "miar_registry.json"
_CLOSURE = _GOV / "closure_authority_index.json"
_CONTRACTS = _GOV / "change_contracts.json"
_MODULE_STUBS = _GOV / "module_attribution_stubs.jsonl"
_SCRIPT_STUBS = _GOV / "script_registry_stubs.jsonl"
_FINDINGS_DOC = _ROOT / "docs" / "current-findings.md"
_BOOK_README = _ROOT / "docs" / "book" / "README.md"
_GRAPH_DOT = _ROOT / "graph.dot"
# gitignored projections — used when present, gracefully skipped when not
_HYPOTHESIS_JSONL = _ROOT / "data" / "hypothesis_registry.jsonl"
_FRAMEWORK_JSONL = _ROOT / "data" / "framework_registry.jsonl"
_HYPOTHESIS_SEED = _ROOT / "scripts" / "governance" / "seed_hypothesis_registry.py"
_FRAMEWORK_SEED = _ROOT / "scripts" / "governance" / "seed_framework_registry.py"

# ── enums ───────────────────────────────────────────────────────────────────────────────────
KIND_ENUM = frozenset({"concept", "boundary", "journey", "contract", "file_identity"})
STATUS_ENUM = frozenset({"ACTIVE", "PROPOSED", "SUPERSEDED", "RETIRED"})
TERMINAL_STATUS = frozenset({"SUPERSEDED", "RETIRED"})
BOUNDARY_KIND_ENUM = frozenset(
    {"PRODUCTION", "POLICY", "AUTHORITY", "TRANSPORT", "STORAGE", "OBSERVATION"}
)
AUTHORITY_LAYER_ENUM = frozenset({"WHAT", "HOW", "WHO", "RESEARCH"})
JOURNEY_KIND_ENUM = frozenset({"RUNTIME", "RESEARCH", "GOVERNANCE", "AGENT", "CONFIG"})
CONTRACT_KIND_ENUM = frozenset(
    {"EMISSION", "DECISION", "RISK", "RESEARCH", "GOVERNANCE", "TRANSPORT", "SCHEMA"}
)
ON_FAILURE_ENUM = frozenset({"HALT", "SKIP", "DEGRADE", "REJECT", "FALLBACK"})
ASSUMPTION_STATUS_ENUM = frozenset({"HOLDS", "FALSIFIED", "UNTESTED"})
FEEDER_KIND_ENUM = frozenset({"CONFIG", "ARTIFACT", "TAP", "PARALLEL_RAIL"})
EVIDENCE_TYPE_ENUM = frozenset({"code", "config", "doc", "test", "finding"})

# ── file_identity enums (Semantic File Identity Layer) ────────────────────────────────────────
#: Filename vs actual meaning, per source-verified review — the classification this layer exists
#: to make explicit rather than silently tolerated (e.g. src/engines/rr_engine.py is MISLEADING:
#: it computes candle polarity bounded [0.5,1.0], not economic reward:risk).
FILENAME_SEMANTIC_STATUS_ENUM = frozenset(
    {"ALIGNED", "HISTORICAL", "MISLEADING", "COMPATIBILITY", "SPLIT", "UNKNOWN"}
)
#: What role this module plays relative to the identity it carries.
IDENTITY_ROLE_ENUM = frozenset({"CANONICAL", "ADAPTER", "SHIM", "SPLIT_PART", "DEAD", "UNKNOWN"})
#: 1 = hand-verified from source (load-bearing). 2 = curated but boundary/encyclopedia-backed,
#: not independently source-read. 3 = machine-derived path slug, unreviewed.
IDENTITY_TIER_ENUM = frozenset({1, 2, 3})
IDENTITY_CONFIDENCE_ENUM = frozenset({"HIGH", "MEDIUM", "LOW"})
#: CURATED = a human asserted this record in the YAML. DERIVED = produced by
#: governance.semantic_identity.derive_tier3_identities at seed time, never hand-written.
IDENTITY_PROVENANCE_ENUM = frozenset({"CURATED", "DERIVED"})
SEMANTIC_LAYER_ENUM = frozenset({
    "MARKET_STRUCTURE", "FEATURE_SURFACE", "SCORING", "DECISION", "RISK", "EXECUTION",
    "RUNTIME", "DATA", "CONFIG", "GOVERNANCE", "RESEARCH", "AGENT", "INTEGRATION",
    "UTILITY", "UNCLASSIFIED",
})

#: Pinned literal. §6.5 Authority Ladder — this layer never earns production authority.
AUTHORITY = "advisory"
SCHEMA_VERSION = "semantic_os/1.1"

SUMMARY_50_MAX = 320
SUMMARY_200_MAX = 1400

_ID_RE = {
    "concept": re.compile(r"^CN-\d{3}$"),
    "boundary": re.compile(r"^BD-\d{3}$"),
    "journey": re.compile(r"^JN-\d{3}$"),
    "contract": re.compile(r"^CT-\d{3}$"),
    # dotted lowercase slug, >=2 segments (the dot buys disjointness from single-token MIAR
    # entry ids like "crt"/"gaussian" — verified zero collisions across all foreign namespaces).
    "file_identity": re.compile(r"^[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*){1,4}$"),
}
_STEP_ID_RE = re.compile(r"^JN-\d{3}\.S\d{2}$")

_CONCEPT_REQUIRED = (
    "id", "kind", "name", "aliases", "status", "supersedes", "superseded_by", "authority",
    "why_it_exists", "problem_it_solves", "explicit_non_goals",
    "miar_stage", "miar_entry", "closure_surface_id", "ontology_ids",
    "owner_boundary", "related_boundaries", "canonical_source",
    "invariants", "preconditions", "postconditions", "assumptions",
    "behavior", "failure_modes",
    "why_this_design", "alternatives_rejected", "research_findings", "hypotheses", "framework_ids",
    "summary_50", "summary_200", "retrieval_keywords", "semantic_tags",
    "book_chapter", "topic_doc", "intent_chain", "intent_domain_doc", "related_concepts",
    "orphan_justification",
)
_BOUNDARY_REQUIRED = (
    "id", "kind", "name", "boundary_kind", "status", "authority", "authority_layer",
    "owner", "owner_symbol", "members", "members_exclude", "consumers",
    "invariant_protected", "invariant_violation_symptom", "contract",
    "concepts", "closure_surface_id", "miar_stage", "change_classes",
    "evidence", "findings", "why_this_boundary", "supersedes", "superseded_by",
)
_JOURNEY_REQUIRED = (
    "id", "kind", "name", "journey_kind", "status", "authority", "source_doc",
    "trigger", "terminal_outcomes", "why_this_path", "steps", "async_feeders",
    "supersedes", "superseded_by",
)
_STEP_REQUIRED = (
    "step_id", "order", "name", "concept", "boundary", "failure_mode", "on_failure", "next",
)
#: Nested shape still required on Boundary.inline ``contract:`` blocks (backward compatible).
_BOUNDARY_INLINE_CONTRACT_REQUIRED = (
    "inputs", "outputs", "guarantees", "non_guarantees", "enforced_by_tests",
)
#: First-class CT-* record fields (SEMANTIC_OS_V1_DESIGN PR-2).
_CONTRACT_RECORD_REQUIRED = (
    "id", "kind", "name", "contract_kind", "status", "authority", "authority_layer",
    "governs_concepts", "governs_boundaries",
    "inputs", "outputs", "guarantees", "non_guarantees", "enforced_by_tests",
    "findings", "why_this_contract", "supersedes", "superseded_by",
)
# Back-compat alias used by older call sites / docs
_CONTRACT_REQUIRED = _BOUNDARY_INLINE_CONTRACT_REQUIRED

#: First-class FileIdentity record fields (Semantic File Identity Layer).
#: Deliberately EXCLUDES owner_boundary / encyclopedia_id / script_registry_id / imports /
#: tests / package / bytes — all DERIVED exact-path joins computed in semantic_objects.py.
#: miar_entry is the only hand-authored cross-link.
_FILE_IDENTITY_REQUIRED = (
    "id", "kind", "semantic_name", "physical_path", "status", "authority",
    "tier", "confidence", "provenance", "derivation",
    "canonical", "role", "semantic_layer",
    "filename_semantic_status", "filename_status_reason",
    "aliases", "concept_ids", "miar_entry",
    "summary_50", "why_this_identity", "evidence",
    "supersedes", "superseded_by",
)

#: The hand-author rule, mechanised. Any of these appearing in a hand-authored YAML record is a
#: schema violation — they are DERIVED at query time from code and existing registries.
_FORBIDDEN_HAND_FIELDS = frozenset({
    "objects", "modules", "authoritative_modules", "tests", "config_keys", "consumers_resolved",
    "dependencies", "imports", "reachability", "book_status", "citations", "bytes", "package",
    "owner_surface", "evidence_count", "journey_steps", "entry_points", "blast_radius",
    "members_resolved", "member_count", "import_fan_in", "import_fan_out",
    "cross_boundary_imports", "config_keys_read", "test_files", "uncovered_members",
    "orphan_members", "objects_traversed", "config_keys_on_path", "required_checks_union",
    "invariants_on_path", "encyclopedia_id", "script_registry_id", "semantic_id",
})

#: Load-bearing spine modules that MUST be claimed by some boundary. Monotonic ratchet:
#: this floor may grow, never shrink (mirrors ``module_attribution._ATTRIBUTED_FLOOR``).
SPINE_FILES = (
    "src/config_layer/crt_engine_v2.py",
    "src/config_layer/execution_planner.py",
    "src/config_layer/production_config.py",
    "src/core/decision_engine.py",
    "src/core/engine_runner.py",
    "src/core/fusion_engine.py",
    "src/core/ultron_risk_gate.py",
    "src/features/feature_pipeline.py",
    "src/features/feature_schema.py",
    "src/runtime/backtest_v2.py",
    "src/runtime/live_engine_hook.py",
)
_BOUNDARY_COVERAGE_FLOOR = len(SPINE_FILES)
#: Monotonic ratchet: every SPINE_FILES module must carry a Tier-1 HIGH curated file_identity.
_IDENTITY_TIER1_FLOOR = len(SPINE_FILES)

_DRIFT_WINDOW = 30


# ── external-authority readers ──────────────────────────────────────────────────────────────

def _read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001 — absence/corruption degrades to "no ids", never crashes
        return None


def _read_jsonl(path: Path) -> list[dict]:
    out: list[dict] = []
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                try:
                    out.append(json.loads(line))
                except Exception:  # noqa: BLE001
                    continue
    except Exception:  # noqa: BLE001
        return []
    return out


def load_ontology(path: Path = _ONTOLOGY) -> dict:
    import yaml  # lazy: keeps the pure-validation path PyYAML-free until first use

    try:
        return yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except Exception:  # noqa: BLE001
        return {}


def ontology_ids(path: Path = _ONTOLOGY) -> set[str]:
    """Every ``id:`` declared anywhere in the market ontology (FM-/SEM-/UNK-/RC-/IND-)."""
    found: set[str] = set()

    def _walk(node: Any) -> None:
        if isinstance(node, dict):
            rid = node.get("id")
            if isinstance(rid, str) and rid:
                found.add(rid)
            for value in node.values():
                _walk(value)
        elif isinstance(node, list):
            for value in node:
                _walk(value)

    _walk(load_ontology(path))
    return found


def miar_stages(path: Path = _MIAR) -> set[str]:
    data = _read_json(path) or {}
    stages = data.get("stages")
    if isinstance(stages, dict):
        return set(stages)
    if isinstance(stages, list):
        return {str(s) for s in stages}
    if isinstance(stages, str):
        return {s.strip() for s in stages.split(",") if s.strip()}
    return set()


def miar_entry_ids(path: Path = _MIAR) -> set[str]:
    data = _read_json(path) or {}
    out: set[str] = set()
    for key in ("entries", "sidecar_entries"):
        block = data.get(key)
        if isinstance(block, list):
            out |= {e.get("id") for e in block if isinstance(e, dict) and e.get("id")}
        elif isinstance(block, dict):
            out |= {k for k in block}
    return out


def closure_surface_ids(path: Path = _CLOSURE) -> set[str]:
    data = _read_json(path) or {}
    surfaces = data.get("surfaces")
    if isinstance(surfaces, list):
        return {s.get("surface_id") for s in surfaces if isinstance(s, dict) and s.get("surface_id")}
    if isinstance(surfaces, dict):
        return set(surfaces)
    return set()


def change_class_names(path: Path = _CONTRACTS) -> set[str]:
    data = _read_json(path) or {}
    classes = data.get("change_classes")
    return set(classes) if isinstance(classes, dict) else set()


def required_checks_for_classes(classes: Iterable[str], path: Path = _CONTRACTS) -> list[str]:
    """Union of ``required_checks`` across the given change classes (L6 reuses this)."""
    data = _read_json(path) or {}
    contracts = data.get("change_classes") or {}
    out: set[str] = set()
    for name in classes:
        entry = contracts.get(name)
        if isinstance(entry, dict):
            out |= set(entry.get("required_checks") or [])
    return sorted(out)


def _prefixed_ids_from(paths: Iterable[Path], pattern: re.Pattern[str]) -> set[str]:
    out: set[str] = set()
    for p in paths:
        try:
            out |= set(pattern.findall(p.read_text(encoding="utf-8")))
        except Exception:  # noqa: BLE001
            continue
    return out


def foreign_id_namespace() -> dict[str, set[str]]:
    """Every id owned by another registry — CN/BD/JN must be disjoint from all of these.

    Sources are TRACKED files wherever possible so the check has full strength on a fresh clone.
    ``H-`` and framework ids fall back to a regex over their (tracked) seed scripts when the
    gitignored ``data/*.jsonl`` projection is absent.
    """
    mod_ids = {r.get("id") for r in _read_jsonl(_MODULE_STUBS) if r.get("id")}
    scr_ids = {r.get("id") for r in _read_jsonl(_SCRIPT_STUBS) if r.get("id")}

    hyp = {r.get("id") for r in _read_jsonl(_HYPOTHESIS_JSONL) if r.get("id")}
    if not hyp:
        hyp = _prefixed_ids_from([_HYPOTHESIS_SEED], re.compile(r"\bH-\d{3}\b"))

    fw = {r.get("id") for r in _read_jsonl(_FRAMEWORK_JSONL) if r.get("id")}
    if not fw:
        fw = _prefixed_ids_from(
            [_FRAMEWORK_SEED],
            re.compile(r"\b(?:KERNEL|DOMAIN|STYLE|STRATEGY|IMPL|INTENT|RISK|EXEC|COMP)-\d{3}\b"),
        )

    return {
        "ontology": ontology_ids(),
        "findings": valid_finding_ids(_FINDINGS_DOC),
        "module_attribution": {i for i in mod_ids if i},
        "script_registry": {i for i in scr_ids if i},
        "miar": miar_entry_ids(),
        "closure": closure_surface_ids(),
        "change_classes": change_class_names(),
        "hypotheses": {i for i in hyp if i},
        "framework": {i for i in fw if i},
    }


def hypothesis_ids() -> set[str]:
    return foreign_id_namespace()["hypotheses"]


def framework_ids() -> set[str]:
    return foreign_id_namespace()["framework"]


def book_toc_chapters(path: Path = _BOOK_README) -> set[str]:
    """Chapter paths linked from the book README's table of contents."""
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:  # noqa: BLE001
        return set()
    out: set[str] = set()
    for target in re.findall(r"\]\(([^)]+\.md)\)", text):
        target = target.split("#", 1)[0].strip()
        if not target:
            continue
        rel = (path.parent / target).resolve()
        try:
            out.add(rel.relative_to(_ROOT).as_posix())
        except ValueError:
            continue
    return out


def graph_dot_modules(path: Path = _GRAPH_DOT) -> set[str]:
    """Dotted module names declared as nodes in ``graph.dot`` (src/-scoped by construction)."""
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:  # noqa: BLE001
        return set()
    out: set[str] = set()
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped.startswith('"') or "->" in stripped:
            continue
        match = re.match(r'^"([A-Za-z_][\w.]*)"\s*;?\s*$', stripped)
        if match:
            out.add(match.group(1))
    return out


def path_to_dotted(rel_path: str) -> Optional[str]:
    """``src/core/engine_runner.py`` -> ``core.engine_runner``; ``src/agent/__init__.py`` -> ``agent``.

    Mirrors the module naming used by ``scripts/analysis/gen_code_map.py``.
    """
    posix = rel_path.replace("\\", "/")
    if not posix.startswith("src/") or not posix.endswith(".py"):
        return None
    trimmed = posix[len("src/"):-len(".py")]
    if trimmed.endswith("/__init__"):
        trimmed = trimmed[: -len("/__init__")]
    if not trimmed or trimmed == "__init__":
        return None
    return trimmed.replace("/", ".")


# ── glob resolution ─────────────────────────────────────────────────────────────────────────

def resolve_members(
    members: Iterable[str],
    members_exclude: Iterable[str] = (),
    root: Path = _ROOT,
) -> list[str]:
    """Resolve member globs/paths to sorted repo-relative POSIX paths (deterministic)."""
    hits: set[str] = set()
    for pattern in members:
        pattern = str(pattern).replace("\\", "/")
        if any(ch in pattern for ch in "*?["):
            for match in root.glob(pattern):
                if match.is_file():
                    hits.add(match.relative_to(root).as_posix())
        else:
            candidate = root / pattern
            if candidate.is_file():
                hits.add(pattern)
    excluded: set[str] = set()
    for pattern in members_exclude:
        pattern = str(pattern).replace("\\", "/")
        if any(ch in pattern for ch in "*?["):
            for match in root.glob(pattern):
                excluded.add(match.relative_to(root).as_posix())
        else:
            excluded.add(pattern)
    return sorted(hits - excluded)


def _resolve_repo_path(path_str: str, root: Path = _ROOT) -> Optional[Path]:
    if not path_str:
        return None
    candidate = root / str(path_str).replace("\\", "/")
    return candidate if candidate.exists() else None


# ── registry ────────────────────────────────────────────────────────────────────────────────

class SemanticOSRegistry:
    """In-memory view of the hand-authored YAML sources + graph validators."""

    def __init__(
        self,
        concepts: list[dict],
        boundaries: list[dict],
        journeys: list[dict],
        contracts: list[dict] | None = None,
        file_identities: list[dict] | None = None,
    ) -> None:
        self.concepts = {r["id"]: r for r in concepts if r.get("id")}
        self.boundaries = {r["id"]: r for r in boundaries if r.get("id")}
        self.journeys = {r["id"]: r for r in journeys if r.get("id")}
        self.contracts = {r["id"]: r for r in (contracts or []) if r.get("id")}
        self.file_identities = {r["id"]: r for r in (file_identities or []) if r.get("id")}
        self._root = _ROOT

    # ------------------------------------------------------------------ load / query

    @classmethod
    def load(cls, directory: "Path | str | None" = None) -> "SemanticOSRegistry":
        import yaml

        base = Path(directory) if directory else _SEMANTIC_DIR

        def _load(name: str, key: str) -> list[dict]:
            path = base / name
            if not path.exists():
                return []
            data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
            records = data.get(key) or []
            return [r for r in records if isinstance(r, dict)]

        return cls(
            _load("concepts.yaml", "concepts"),
            _load("boundaries.yaml", "boundaries"),
            _load("journeys.yaml", "journeys"),
            _load("contracts.yaml", "contracts"),
            _load("file_identities.yaml", "file_identities"),
        )

    @property
    def records(self) -> list[dict]:
        return (
            sorted(self.concepts.values(), key=lambda r: r["id"])
            + sorted(self.boundaries.values(), key=lambda r: r["id"])
            + sorted(self.journeys.values(), key=lambda r: r["id"])
            + sorted(self.contracts.values(), key=lambda r: r["id"])
            + sorted(self.file_identities.values(), key=lambda r: r["id"])
        )

    def get(self, record_id: str) -> dict:
        for table in (self.concepts, self.boundaries, self.journeys, self.contracts, self.file_identities):
            if record_id in table:
                return table[record_id]
        raise KeyError(f"no semantic record with id {record_id!r}")

    def identity_by_path(self) -> dict[str, str]:
        """``physical_path -> canonical file_identity id`` (curated + derived; deterministic)."""
        out: dict[str, str] = {}
        for rid, identity in sorted(self.file_identities.items()):
            if identity.get("canonical") is not True:
                continue
            path = str(identity.get("physical_path") or "").replace("\\", "/")
            if path:
                out[path] = rid
        return out

    def filter(
        self,
        kind: Optional[str] = None,
        miar_stage: Optional[str] = None,
        closure_surface_id: Optional[str] = None,
        status: Optional[str] = None,
        tag: Optional[str] = None,
    ) -> list[dict]:
        out = self.records
        if kind is not None:
            out = [r for r in out if r.get("kind") == kind]
        if miar_stage is not None:
            out = [r for r in out if r.get("miar_stage") == miar_stage]
        if closure_surface_id is not None:
            out = [r for r in out if r.get("closure_surface_id") == closure_surface_id]
        if status is not None:
            out = [r for r in out if r.get("status") == status]
        if tag is not None:
            out = [r for r in out if tag in (r.get("semantic_tags") or [])]
        return sorted(out, key=lambda r: r.get("id", ""))

    def steps(self) -> list[tuple[dict, dict]]:
        """Flat ``(journey, step)`` pairs across every journey."""
        out: list[tuple[dict, dict]] = []
        for journey in sorted(self.journeys.values(), key=lambda r: r["id"]):
            for step in journey.get("steps") or []:
                if isinstance(step, dict):
                    out.append((journey, step))
        return out

    def boundary_for_object(self, rel_path: str) -> Optional[str]:
        """Which boundary claims this file (single-ownership is enforced by validator 7)."""
        rel_path = rel_path.replace("\\", "/")
        for bid, boundary in sorted(self.boundaries.items()):
            members = resolve_members(
                boundary.get("members") or [], boundary.get("members_exclude") or [], self._root
            )
            if rel_path in members:
                return bid
        return None

    def summary(self) -> dict:
        claimed: set[str] = set()
        for boundary in self.boundaries.values():
            claimed |= set(
                resolve_members(
                    boundary.get("members") or [],
                    boundary.get("members_exclude") or [],
                    self._root,
                )
            )
        tier1_paths = {
            str(r.get("physical_path") or "").replace("\\", "/")
            for r in self.file_identities.values() if r.get("tier") == 1
        }
        return {
            "concepts": len(self.concepts),
            "boundaries": len(self.boundaries),
            "journeys": len(self.journeys),
            "contracts": len(self.contracts),
            "journey_steps": len(self.steps()),
            "claimed_objects": len(claimed),
            "spine_files": len(SPINE_FILES),
            "spine_claimed": sum(1 for f in SPINE_FILES if f in claimed),
            "file_identities": len(self.file_identities),
            "file_identities_tier1": sum(1 for r in self.file_identities.values() if r.get("tier") == 1),
            "file_identities_tier2": sum(1 for r in self.file_identities.values() if r.get("tier") == 2),
            "spine_identified": sum(1 for f in SPINE_FILES if f in tier1_paths),
            "authority": AUTHORITY,
            "schema_version": SCHEMA_VERSION,
        }

    # ------------------------------------------------------------------ 14 validators

    def validate_schema(self) -> list[ValidationError]:
        """(1) Required fields, enums, types, pinned authority, summary caps."""
        errors: list[ValidationError] = []
        for record in self.records:
            try:
                validate_record(record)
            except ValueError as exc:
                errors.append(ValidationError(record.get("id", "?"), "schema", str(exc)))
        return errors

    def validate_unique_ids_global(self) -> list[ValidationError]:
        """(2) CN/BD/JN/step ids unique among themselves AND disjoint from every other registry."""
        errors: list[ValidationError] = []
        seen: dict[str, str] = {}
        for record in self.records:
            rid = record.get("id")
            if not rid:
                continue
            if rid in seen:
                errors.append(
                    ValidationError(rid, "duplicate", f"id reused (also {seen[rid]})")
                )
            seen[rid] = record.get("kind", "?")
        for journey, step in self.steps():
            sid = step.get("step_id")
            if not sid:
                continue
            if sid in seen:
                errors.append(
                    ValidationError(sid, "duplicate", f"step_id collides with {seen[sid]} id")
                )
            seen[sid] = "step"

        foreign = foreign_id_namespace()
        for rid, kind in sorted(seen.items()):
            for source, ids in sorted(foreign.items()):
                if rid in ids:
                    errors.append(
                        ValidationError(
                            rid,
                            "duplicate",
                            f"{kind} id collides with the {source} namespace — ids must be globally unique",
                        )
                    )
        return errors

    def validate_no_orphan_concepts(self) -> list[ValidationError]:
        """(3) Every concept is reachable from a boundary AND a journey step (or justified)."""
        errors: list[ValidationError] = []
        by_boundary: set[str] = set()
        for boundary in self.boundaries.values():
            by_boundary |= {c for c in (boundary.get("concepts") or [])}
        by_step = {step.get("concept") for _, step in self.steps()}

        for cid, concept in sorted(self.concepts.items()):
            if concept.get("status") in TERMINAL_STATUS:
                continue
            justification = (concept.get("orphan_justification") or "").strip()
            if cid not in by_boundary and not justification:
                errors.append(
                    ValidationError(cid, "orphan", "no boundary references this concept and no orphan_justification")
                )
            if cid not in by_step and not justification:
                errors.append(
                    ValidationError(cid, "orphan", "no journey step references this concept and no orphan_justification")
                )

        for bid, boundary in sorted(self.boundaries.items()):
            if boundary.get("status") in TERMINAL_STATUS:
                continue
            if not (boundary.get("concepts") or []):
                errors.append(ValidationError(bid, "orphan", "boundary declares no concepts"))
            members = resolve_members(
                boundary.get("members") or [], boundary.get("members_exclude") or [], self._root
            )
            if not members:
                errors.append(ValidationError(bid, "orphan", "boundary resolves to zero member files"))

        for jid, journey in sorted(self.journeys.items()):
            if journey.get("status") in TERMINAL_STATUS:
                continue
            if len(journey.get("steps") or []) < 2:
                errors.append(ValidationError(jid, "orphan", "journey has fewer than 2 steps"))
        return errors

    def validate_no_cyclic_ownership(self) -> list[ValidationError]:
        """(4) The boundary CONSUMER graph (BD -> consumers -> BD) must be acyclic.

        Deliberately NOT over the CN<->BD membership relation: ``validate_bidirectional_consistency``
        (validator 5) *requires* ``CN.owner_boundary == BD`` and ``CN in BD.concepts``, so that pair
        is a 2-cycle by construction on every correctly-authored concept. Membership is a symmetric
        declaration, not a dependency.

        Consumer cycles are the real defect: if A consumes B consumes A, "what breaks if I change
        A" has no well-defined answer and L6's blast radius would not terminate.
        """
        errors: list[ValidationError] = []
        graph: dict[str, list[str]] = {}
        for bid, boundary in self.boundaries.items():
            edges: list[str] = []
            for consumer in boundary.get("consumers") or []:
                if not isinstance(consumer, str) or not consumer.startswith("BD-"):
                    continue  # explicit paths are not boundary edges
                if consumer == bid:
                    errors.append(
                        ValidationError(bid, "cycle", "boundary lists itself as a consumer")
                    )
                    continue
                edges.append(consumer)
            graph[bid] = edges

        WHITE, GREY, BLACK = 0, 1, 2
        colour: dict[str, int] = {n: WHITE for n in graph}

        def _visit(node: str, trail: list[str]) -> None:
            colour[node] = GREY
            for nxt in graph.get(node, []):
                if nxt not in colour:
                    continue  # dangling FK — reported by validator 6, not here
                if colour[nxt] == GREY:
                    cycle = trail[trail.index(nxt):] if nxt in trail else [nxt]
                    errors.append(
                        ValidationError(
                            node, "cycle", f"consumer cycle: {' -> '.join(cycle + [nxt])}"
                        )
                    )
                elif colour[nxt] == WHITE:
                    _visit(nxt, trail + [nxt])
            colour[node] = BLACK

        for node in sorted(graph):
            if colour[node] == WHITE:
                _visit(node, [node])
        return errors

    def validate_bidirectional_consistency(self) -> list[ValidationError]:
        """(5) ``CN.owner_boundary == BD`` iff ``CN in BD.concepts``."""
        errors: list[ValidationError] = []
        for cid, concept in sorted(self.concepts.items()):
            owner = concept.get("owner_boundary")
            if not owner:
                continue
            boundary = self.boundaries.get(owner)
            if boundary is None:
                continue  # dangling FK — validator 6
            if cid not in (boundary.get("concepts") or []):
                errors.append(
                    ValidationError(
                        cid, "bidirectional",
                        f"owner_boundary {owner} does not list {cid} in its concepts",
                    )
                )
        for bid, boundary in sorted(self.boundaries.items()):
            for cid in boundary.get("concepts") or []:
                concept = self.concepts.get(cid)
                if concept is None:
                    continue
                owner = concept.get("owner_boundary")
                related = concept.get("related_boundaries") or []
                if owner != bid and bid not in related:
                    errors.append(
                        ValidationError(
                            bid, "bidirectional",
                            f"lists concept {cid}, but {cid} names neither it as owner_boundary nor in related_boundaries",
                        )
                    )
        return errors

    def validate_fk_resolution(self) -> list[ValidationError]:
        """(6) Every foreign key resolves against its owning authority."""
        errors: list[ValidationError] = []
        stages = miar_stages()
        entries = miar_entry_ids()
        surfaces = closure_surface_ids()
        onto = ontology_ids()
        findings = valid_finding_ids(_FINDINGS_DOC)
        classes = change_class_names()
        foreign = foreign_id_namespace()
        hyps = foreign["hypotheses"]
        fws = foreign["framework"]
        toc = book_toc_chapters()

        def _check_set(rid: str, values: Iterable[str], known: set[str], label: str) -> None:
            if not known:
                return  # authority unavailable — validator 13 reports missing artifacts
            for value in values or []:
                if value not in known:
                    errors.append(ValidationError(rid, "fk", f"unknown {label}: {value}"))

        def _check_path(rid: str, value: Optional[str], label: str) -> None:
            if not value:
                return
            if _resolve_repo_path(value) is None:
                errors.append(ValidationError(rid, "fk", f"{label} path does not exist: {value}"))

        for rid, concept in sorted(self.concepts.items()):
            if concept.get("miar_stage") and stages and concept["miar_stage"] not in stages:
                errors.append(
                    ValidationError(rid, "fk", f"unknown miar_stage: {concept['miar_stage']}")
                )
            if concept.get("miar_entry") and entries and concept["miar_entry"] not in entries:
                errors.append(
                    ValidationError(rid, "fk", f"unknown miar_entry: {concept['miar_entry']}")
                )
            if concept.get("closure_surface_id") and surfaces and concept["closure_surface_id"] not in surfaces:
                errors.append(
                    ValidationError(rid, "fk", f"unknown closure_surface_id: {concept['closure_surface_id']}")
                )
            _check_set(rid, concept.get("ontology_ids"), onto, "ontology id")
            _check_set(rid, concept.get("research_findings"), findings, "finding")
            _check_set(rid, concept.get("hypotheses"), hyps, "hypothesis")
            _check_set(rid, concept.get("framework_ids"), fws, "framework id")
            for bid in [concept.get("owner_boundary")] + list(concept.get("related_boundaries") or []):
                if bid and bid not in self.boundaries:
                    errors.append(ValidationError(rid, "fk", f"unknown boundary: {bid}"))
            for other in concept.get("related_concepts") or []:
                if other not in self.concepts:
                    errors.append(ValidationError(rid, "fk", f"unknown related concept: {other}"))
            for assumption in concept.get("assumptions") or []:
                fid = (assumption or {}).get("falsified_by")
                if fid and findings and fid not in findings:
                    errors.append(ValidationError(rid, "fk", f"unknown finding in assumption: {fid}"))
            for mode in concept.get("failure_modes") or []:
                fid = (mode or {}).get("finding")
                if fid and findings and fid not in findings:
                    errors.append(ValidationError(rid, "fk", f"unknown finding in failure_mode: {fid}"))
            _check_path(rid, concept.get("canonical_source"), "canonical_source")
            _check_path(rid, concept.get("topic_doc"), "topic_doc")
            _check_path(rid, concept.get("intent_domain_doc"), "intent_domain_doc")
            chapter = concept.get("book_chapter")
            if chapter:
                if _resolve_repo_path(chapter) is None:
                    errors.append(ValidationError(rid, "fk", f"book_chapter does not exist: {chapter}"))
                elif toc and chapter.replace("\\", "/") not in toc:
                    errors.append(
                        ValidationError(rid, "fk", f"book_chapter not linked from docs/book/README.md TOC: {chapter}")
                    )

        for rid, boundary in sorted(self.boundaries.items()):
            if boundary.get("miar_stage") and stages and boundary["miar_stage"] not in stages:
                errors.append(
                    ValidationError(rid, "fk", f"unknown miar_stage: {boundary['miar_stage']}")
                )
            if boundary.get("closure_surface_id") and surfaces and boundary["closure_surface_id"] not in surfaces:
                errors.append(
                    ValidationError(rid, "fk", f"unknown closure_surface_id: {boundary['closure_surface_id']}")
                )
            _check_set(rid, boundary.get("change_classes"), classes, "change class")
            _check_set(rid, boundary.get("findings"), findings, "finding")
            for cid in boundary.get("concepts") or []:
                if cid not in self.concepts:
                    errors.append(ValidationError(rid, "fk", f"unknown concept: {cid}"))
            for consumer in boundary.get("consumers") or []:
                if isinstance(consumer, str) and consumer.startswith("BD-") and consumer not in self.boundaries:
                    errors.append(ValidationError(rid, "fk", f"unknown consumer boundary: {consumer}"))
            for ctid in boundary.get("contract_ids") or []:
                if ctid not in self.contracts:
                    errors.append(ValidationError(rid, "fk", f"unknown contract_ids entry: {ctid}"))
            _check_path(rid, boundary.get("owner"), "owner")
            for test_path in (boundary.get("contract") or {}).get("enforced_by_tests") or []:
                _check_path(rid, test_path, "enforced_by_tests")

        for rid, journey in sorted(self.journeys.items()):
            _check_path(rid, journey.get("source_doc"), "source_doc")

        for rid, contract in sorted(self.contracts.items()):
            if contract.get("status") in TERMINAL_STATUS:
                continue
            for cid in contract.get("governs_concepts") or []:
                if cid not in self.concepts:
                    errors.append(ValidationError(rid, "fk", f"unknown governs_concepts entry: {cid}"))
            for bid in contract.get("governs_boundaries") or []:
                if bid not in self.boundaries:
                    errors.append(ValidationError(rid, "fk", f"unknown governs_boundaries entry: {bid}"))
            _check_set(rid, contract.get("findings"), findings, "finding")
            for test_path in contract.get("enforced_by_tests") or []:
                _check_path(rid, test_path, "enforced_by_tests")
            if contract.get("closure_surface_id") and surfaces and contract["closure_surface_id"] not in surfaces:
                errors.append(
                    ValidationError(rid, "fk", f"unknown closure_surface_id: {contract['closure_surface_id']}")
                )

        for rid, identity in sorted(self.file_identities.items()):
            if identity.get("status") in TERMINAL_STATUS:
                continue
            entry = identity.get("miar_entry")
            if entry and entries and entry not in entries:
                errors.append(ValidationError(rid, "fk", f"unknown miar_entry: {entry}"))
            _check_set(rid, identity.get("concept_ids"), set(self.concepts), "concept")
            sup = identity.get("superseded_by")
            if sup and sup not in self.file_identities:
                errors.append(ValidationError(rid, "fk", f"unknown superseded_by: {sup}"))
        return errors

    def validate_boundary_members(self) -> list[ValidationError]:
        """(7) Globs resolve, explicit paths exist, and no file is claimed by two boundaries."""
        errors: list[ValidationError] = []
        owner_of: dict[str, str] = {}
        for bid, boundary in sorted(self.boundaries.items()):
            excludes = boundary.get("members_exclude") or []
            for pattern in boundary.get("members") or []:
                resolved = resolve_members([pattern], excludes, self._root)
                if not resolved:
                    errors.append(
                        ValidationError(bid, "members", f"member pattern matches no file: {pattern}")
                    )
            for path in resolve_members(boundary.get("members") or [], excludes, self._root):
                if path in owner_of and owner_of[path] != bid:
                    errors.append(
                        ValidationError(
                            bid, "members",
                            f"{path} is already claimed by {owner_of[path]} — single-ownership violated",
                        )
                    )
                else:
                    owner_of[path] = bid
        return errors

    def validate_spine_coverage(self) -> list[ValidationError]:
        """(8) Every load-bearing spine module is boundary-claimed (monotonic ratchet)."""
        errors: list[ValidationError] = []
        claimed: set[str] = set()
        for boundary in self.boundaries.values():
            claimed |= set(
                resolve_members(
                    boundary.get("members") or [],
                    boundary.get("members_exclude") or [],
                    self._root,
                )
            )
        covered = [f for f in SPINE_FILES if f in claimed]
        for path in SPINE_FILES:
            if path not in claimed:
                errors.append(
                    ValidationError("SPINE", "coverage", f"spine module not claimed by any boundary: {path}")
                )
        if len(covered) < _BOUNDARY_COVERAGE_FLOOR and not errors:
            errors.append(
                ValidationError(
                    "SPINE", "coverage",
                    f"spine coverage regressed: {len(covered)} < floor {_BOUNDARY_COVERAGE_FLOOR}",
                )
            )
        return errors

    def validate_journey_dag(self) -> list[ValidationError]:
        """(9) Contiguous order, in-journey targets, acyclic, all reachable, forward-only, terminal."""
        errors: list[ValidationError] = []
        for jid, journey in sorted(self.journeys.items()):
            steps = [s for s in (journey.get("steps") or []) if isinstance(s, dict)]
            if not steps:
                continue
            orders = [s.get("order") for s in steps]
            if sorted(orders) != list(range(1, len(steps) + 1)):
                errors.append(
                    ValidationError(jid, "journey", f"order must be contiguous 1..{len(steps)}, got {sorted(orders)}")
                )
            ids = [s.get("step_id") for s in steps]
            if len(set(ids)) != len(ids):
                errors.append(ValidationError(jid, "journey", "duplicate step_id within journey"))
            by_id = {s.get("step_id"): s for s in steps}
            order_of = {s.get("step_id"): s.get("order") for s in steps}

            for step in steps:
                sid = step.get("step_id")
                for nxt in step.get("next") or []:
                    if nxt not in by_id:
                        errors.append(
                            ValidationError(jid, "journey", f"{sid} -> unknown step {nxt}")
                        )
                        continue
                    a, b = order_of.get(sid), order_of.get(nxt)
                    if isinstance(a, int) and isinstance(b, int) and b <= a:
                        errors.append(
                            ValidationError(
                                jid, "journey",
                                f"{sid} (order {a}) -> {nxt} (order {b}) is not strictly forward",
                            )
                        )
            # reachability from order 1
            start = next((s.get("step_id") for s in steps if s.get("order") == 1), None)
            if start is None:
                errors.append(ValidationError(jid, "journey", "no step with order 1"))
            else:
                reached = {start}
                frontier = [start]
                while frontier:
                    cur = frontier.pop()
                    for nxt in (by_id.get(cur) or {}).get("next") or []:
                        if nxt in by_id and nxt not in reached:
                            reached.add(nxt)
                            frontier.append(nxt)
                for sid in ids:
                    if sid not in reached:
                        errors.append(
                            ValidationError(jid, "journey", f"step {sid} is unreachable from order 1")
                        )
            if not any(not (s.get("next") or []) for s in steps):
                errors.append(ValidationError(jid, "journey", "no terminal step (every step has a successor)"))
            if not (journey.get("terminal_outcomes") or []):
                errors.append(ValidationError(jid, "journey", "terminal_outcomes is empty"))
            for feeder in journey.get("async_feeders") or []:
                joins = (feeder or {}).get("joins_at_step")
                if joins and joins not in by_id:
                    errors.append(
                        ValidationError(jid, "journey", f"async feeder joins unknown step {joins}")
                    )
        return errors

    def validate_journey_step_fks(self) -> list[ValidationError]:
        """(10) Step concept/boundary resolve; boundary is owned/related; failure_mode is declared."""
        errors: list[ValidationError] = []
        for journey, step in self.steps():
            sid = step.get("step_id", "?")
            cid = step.get("concept")
            bid = step.get("boundary")
            concept = self.concepts.get(cid) if cid else None
            if cid and concept is None:
                errors.append(ValidationError(sid, "step", f"unknown concept {cid}"))
            if bid and bid not in self.boundaries:
                errors.append(ValidationError(sid, "step", f"unknown boundary {bid}"))
            if concept is not None and bid:
                allowed = {concept.get("owner_boundary")} | set(concept.get("related_boundaries") or [])
                if bid not in allowed:
                    errors.append(
                        ValidationError(
                            sid, "step",
                            f"boundary {bid} is neither owner_boundary nor a related_boundary of {cid}",
                        )
                    )
            if concept is not None:
                declared = {(m or {}).get("mode") for m in concept.get("failure_modes") or []}
                mode = step.get("failure_mode")
                if mode and mode not in declared:
                    errors.append(
                        ValidationError(
                            sid, "step",
                            f"failure_mode {mode!r} is not declared in {cid}.failure_modes {sorted(m for m in declared if m)}",
                        )
                    )
        return errors

    def validate_evidence(self) -> list[ValidationError]:
        """(11) Boundary evidence paths resolve; code symbols sit within ±30 lines (reused rule)."""
        errors: list[ValidationError] = []

        def _check(rid: str, path_str: str, symbol: Optional[str], line: Optional[int], etype: str) -> None:
            target = _resolve_repo_path(path_str)
            if target is None:
                errors.append(ValidationError(rid, "evidence", f"path not found: {path_str}"))
                return
            if etype != "code" or not symbol or line is None:
                return
            lines = target.read_text(encoding="utf-8", errors="replace").splitlines()
            if not any(symbol in ln for ln in lines):
                errors.append(ValidationError(rid, "evidence", f"symbol {symbol!r} absent from {path_str}"))
                return
            lo = max(0, line - 1 - _DRIFT_WINDOW)
            hi = min(len(lines), line - 1 + _DRIFT_WINDOW + 1)
            if not any(symbol in lines[k] for k in range(lo, hi)):
                found = [k + 1 for k, ln in enumerate(lines) if symbol in ln]
                errors.append(
                    ValidationError(
                        rid, "evidence",
                        f"{symbol!r} drifted >±{_DRIFT_WINDOW} from line {line} (at {found})",
                    )
                )

        for rid, boundary in sorted(self.boundaries.items()):
            for ev in boundary.get("evidence") or []:
                if not isinstance(ev, dict):
                    continue
                _check(rid, ev.get("path", ""), ev.get("symbol"), ev.get("line"), ev.get("type", "code"))
            owner_symbol = boundary.get("owner_symbol")
            if owner_symbol and boundary.get("owner"):
                target = _resolve_repo_path(boundary["owner"])
                if target is not None:
                    text = target.read_text(encoding="utf-8", errors="replace")
                    if owner_symbol not in text:
                        errors.append(
                            ValidationError(
                                rid, "evidence",
                                f"owner_symbol {owner_symbol!r} absent from {boundary['owner']}",
                            )
                        )
        for rid, identity in sorted(self.file_identities.items()):
            for ev in identity.get("evidence") or []:
                if not isinstance(ev, dict):
                    continue
                _check(rid, ev.get("path", ""), ev.get("symbol"), ev.get("line"), ev.get("type", "code"))
        return errors

    def validate_alias_uniqueness(self) -> list[ValidationError]:
        """(12) Concept + file_identity names/aliases form ONE key domain — collisions fail closed."""
        errors: list[ValidationError] = []
        owner: dict[str, str] = {}
        entries: list[tuple[str, dict]] = (
            sorted(self.concepts.items()) + sorted(self.file_identities.items())
        )
        for rid, record in entries:
            name = record.get("name") or record.get("semantic_name") or ""
            keys = [name] + list(record.get("aliases") or [])
            for key in keys:
                if not key:
                    continue
                norm = str(key).strip().lower()
                if norm in owner and owner[norm] != rid:
                    errors.append(
                        ValidationError(
                            rid, "alias",
                            f"name/alias {key!r} is AMBIGUOUS — already claimed by {owner[norm]}",
                        )
                    )
                else:
                    owner[norm] = rid
        return errors

    def validate_referenced_objects_reachable(self, strict: bool = False) -> list[ValidationError]:
        """(13) Every referenced path exists on disk (HARD); graph.dot staleness (STRICT-only).

        ``graph.dot`` is a GENERATED artifact this layer does not own, and it is independently
        stale (measured 2026-08-08: 347 nodes vs 472 ``src/`` files on disk — 125 modules absent
        because nobody re-ran ``scripts/analysis/gen_code_map.py`` after adding them). Treating
        that as a hard error would make this registry red for a defect in a different artifact,
        so the staleness is reported as ONE aggregated error under ``--strict`` only.

        Import edges themselves do NOT depend on this: ``semantic_objects.ast_import_census()``
        recomputes them from disk on every seed, so ``graph.dot`` is a cross-check, not the
        authority.
        """
        errors: list[ValidationError] = []
        for bid, boundary in sorted(self.boundaries.items()):
            for path in (boundary.get("members") or []):
                path = str(path).replace("\\", "/")
                if any(ch in path for ch in "*?["):
                    continue  # glob emptiness is validator 7's job
                if _resolve_repo_path(path) is None:
                    errors.append(
                        ValidationError(bid, "reachable", f"member path does not exist: {path}")
                    )
        if strict:
            stale = self.graph_staleness()
            if stale:
                errors.append(
                    ValidationError(
                        "graph.dot", "reachable",
                        f"stale_graph: {len(stale)} claimed src/ module(s) are not nodes in graph.dot "
                        f"(e.g. {stale[:3]}) — regenerate with scripts/analysis/gen_code_map.py",
                    )
                )
        return errors

    def graph_staleness(self) -> list[str]:
        """Claimed ``src/`` members absent from ``graph.dot`` — informational, not a gate."""
        nodes = graph_dot_modules()
        if not nodes:
            return []
        stale: set[str] = set()
        for boundary in self.boundaries.values():
            for path in resolve_members(
                boundary.get("members") or [], boundary.get("members_exclude") or [], self._root
            ):
                dotted = path_to_dotted(path)
                if dotted is not None and dotted not in nodes:
                    stale.add(path)
        return sorted(stale)

    def validate_no_derived_in_source(self) -> list[ValidationError]:
        """(14) The hand-author rule, mechanised — no DERIVED field may be hand-written."""
        errors: list[ValidationError] = []
        for record in self.records:
            present = sorted(set(record) & _FORBIDDEN_HAND_FIELDS)
            if present:
                errors.append(
                    ValidationError(
                        record.get("id", "?"), "derived",
                        f"derived field(s) hand-authored (must be generated, never written): {present}",
                    )
                )
        return errors

    def validate_identity_paths(self) -> list[ValidationError]:
        """(15) Every file_identity.physical_path exists on disk, is a .py, not under tests/."""
        errors: list[ValidationError] = []
        for rid, identity in sorted(self.file_identities.items()):
            path = str(identity.get("physical_path") or "").replace("\\", "/")
            if not path:
                continue  # missing-field already reported by validate_schema
            if not path.endswith(".py"):
                errors.append(
                    ValidationError(rid, "identity_path", f"physical_path must end in .py: {path}")
                )
                continue
            if path.startswith("tests/"):
                errors.append(
                    ValidationError(
                        rid, "identity_path",
                        f"physical_path may not be under tests/ — file identities cover code, "
                        f"not tests (decision 3): {path}",
                    )
                )
                continue
            if _resolve_repo_path(path) is None:
                errors.append(ValidationError(rid, "identity_path", f"physical_path does not exist: {path}"))
        return errors

    def validate_identity_canonicality(self) -> list[ValidationError]:
        """(16) Exactly one canonical file_identity per physical_path."""
        errors: list[ValidationError] = []
        by_path: dict[str, list[str]] = {}
        for rid, identity in sorted(self.file_identities.items()):
            path = str(identity.get("physical_path") or "").replace("\\", "/")
            if path:
                by_path.setdefault(path, []).append(rid)
        for path, ids in sorted(by_path.items()):
            canonical_ids = [rid for rid in ids if self.file_identities[rid].get("canonical") is True]
            if len(canonical_ids) == 0:
                errors.append(
                    ValidationError(",".join(ids), "identity_canonical", f"no canonical file_identity for {path}")
                )
            elif len(canonical_ids) > 1:
                errors.append(
                    ValidationError(
                        ",".join(canonical_ids), "identity_canonical",
                        f"multiple canonical file_identities compete for {path}: {canonical_ids}",
                    )
                )
        return errors

    def validate_identity_spine_coverage(self) -> list[ValidationError]:
        """(17) Every SPINE_FILES module carries a Tier-1 HIGH curated file_identity (ratchet)."""
        errors: list[ValidationError] = []
        tier1_paths = {
            str(r.get("physical_path") or "").replace("\\", "/")
            for r in self.file_identities.values() if r.get("tier") == 1
        }
        covered = [f for f in SPINE_FILES if f in tier1_paths]
        for path in SPINE_FILES:
            if path not in tier1_paths:
                errors.append(
                    ValidationError("SPINE", "identity_coverage", f"spine module has no Tier-1 file_identity: {path}")
                )
        if len(covered) < _IDENTITY_TIER1_FLOOR and not errors:
            errors.append(
                ValidationError(
                    "SPINE", "identity_coverage",
                    f"Tier-1 identity spine coverage regressed: {len(covered)} < floor {_IDENTITY_TIER1_FLOOR}",
                )
            )
        return errors

    def validate_all(self, strict: bool = False) -> list[ValidationError]:
        return (
            self.validate_schema()
            + self.validate_unique_ids_global()
            + self.validate_no_orphan_concepts()
            + self.validate_no_cyclic_ownership()
            + self.validate_bidirectional_consistency()
            + self.validate_fk_resolution()
            + self.validate_boundary_members()
            + self.validate_spine_coverage()
            + self.validate_journey_dag()
            + self.validate_journey_step_fks()
            + self.validate_evidence()
            + self.validate_alias_uniqueness()
            + self.validate_referenced_objects_reachable(strict=strict)
            + self.validate_no_derived_in_source()
            + self.validate_identity_paths()
            + self.validate_identity_canonicality()
            + self.validate_identity_spine_coverage()
        )

    # ------------------------------------------------------------------ io

    @staticmethod
    def dump(path: "Path | str", records: list[dict]) -> int:
        """Validate + write deterministically (overwrite, sorted by id, sorted keys)."""
        seen: set[str] = set()
        for record in records:
            validate_record(record)
            if record["id"] in seen:
                raise ValueError(f"duplicate id in seed set: {record['id']}")
            seen.add(record["id"])
        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        ordered = sorted(records, key=lambda r: r["id"])
        with target.open("w", encoding="utf-8", newline="\n") as fh:
            for record in ordered:
                fh.write(json.dumps(record, ensure_ascii=False, sort_keys=True) + "\n")
        return len(ordered)


# ── schema validation ───────────────────────────────────────────────────────────────────────

def _require_list(rid: str, record: dict, field: str) -> None:
    if not isinstance(record.get(field), list):
        raise ValueError(f"{rid}: {field} must be a list")


def _require_str(rid: str, record: dict, field: str, *, allow_empty: bool = False) -> None:
    value = record.get(field)
    if not isinstance(value, str) or (not allow_empty and not value.strip()):
        raise ValueError(f"{rid}: {field} must be a non-empty string")


def validate_record(record: dict) -> None:
    """Raise ``ValueError`` on any schema / enum / type / authority violation."""
    kind = record.get("kind")
    if kind not in KIND_ENUM:
        raise ValueError(f"record {record.get('id')!r}: kind {kind!r} not in {sorted(KIND_ENUM)}")
    rid = record.get("id")
    if not isinstance(rid, str) or not _ID_RE[kind].match(rid or ""):
        raise ValueError(f"{kind} id {rid!r} must match {_ID_RE[kind].pattern}")

    required = {
        "concept": _CONCEPT_REQUIRED,
        "boundary": _BOUNDARY_REQUIRED,
        "journey": _JOURNEY_REQUIRED,
        "contract": _CONTRACT_RECORD_REQUIRED,
        "file_identity": _FILE_IDENTITY_REQUIRED,
    }[kind]
    missing = [f for f in required if f not in record]
    if missing:
        raise ValueError(f"{rid} missing fields: {missing}")

    if record.get("status") not in STATUS_ENUM:
        raise ValueError(f"{rid}: status {record.get('status')!r} not in {sorted(STATUS_ENUM)}")
    if record.get("authority") != AUTHORITY:
        raise ValueError(
            f"{rid}: authority must be the pinned literal {AUTHORITY!r} "
            f"(got {record.get('authority')!r}) — this layer never earns production authority (§6.5)"
        )
    forbidden = sorted(set(record) & _FORBIDDEN_HAND_FIELDS)
    if forbidden:
        raise ValueError(f"{rid}: derived field(s) may not be hand-authored: {forbidden}")

    if kind == "concept":
        _validate_concept(rid, record)
    elif kind == "boundary":
        _validate_boundary(rid, record)
    elif kind == "contract":
        _validate_contract_record(rid, record)
    elif kind == "journey":
        _validate_journey(rid, record)
    else:
        _validate_file_identity(rid, record)


def _validate_concept(rid: str, record: dict) -> None:
    for field in ("name", "why_it_exists", "problem_it_solves", "behavior", "why_this_design",
                  "canonical_source", "owner_boundary", "miar_stage", "summary_50", "summary_200"):
        _require_str(rid, record, field)
    for field in ("aliases", "explicit_non_goals", "ontology_ids", "related_boundaries",
                  "invariants", "preconditions", "postconditions", "assumptions",
                  "failure_modes", "alternatives_rejected", "research_findings", "hypotheses",
                  "framework_ids", "retrieval_keywords", "semantic_tags", "related_concepts"):
        _require_list(rid, record, field)
    if not record.get("invariants"):
        raise ValueError(f"{rid}: invariants must declare at least one entry")
    if len(record["summary_50"]) > SUMMARY_50_MAX:
        raise ValueError(f"{rid}: summary_50 is {len(record['summary_50'])} chars > {SUMMARY_50_MAX}")
    if len(record["summary_200"]) > SUMMARY_200_MAX:
        raise ValueError(f"{rid}: summary_200 is {len(record['summary_200'])} chars > {SUMMARY_200_MAX}")
    for assumption in record["assumptions"]:
        if not isinstance(assumption, dict) or "assumption" not in assumption:
            raise ValueError(f"{rid}: assumption entry missing 'assumption': {assumption!r}")
        status = assumption.get("status")
        if status not in ASSUMPTION_STATUS_ENUM:
            raise ValueError(f"{rid}: assumption status {status!r} not in {sorted(ASSUMPTION_STATUS_ENUM)}")
    modes: set[str] = set()
    for mode in record["failure_modes"]:
        if not isinstance(mode, dict) or not mode.get("mode"):
            raise ValueError(f"{rid}: failure_mode entry missing 'mode': {mode!r}")
        if mode["mode"] in modes:
            raise ValueError(f"{rid}: duplicate failure_mode {mode['mode']!r}")
        modes.add(mode["mode"])
    for alt in record["alternatives_rejected"]:
        if not isinstance(alt, dict) or not alt.get("alternative") or not alt.get("why_rejected"):
            raise ValueError(f"{rid}: alternatives_rejected entry needs 'alternative' + 'why_rejected': {alt!r}")


def _validate_boundary(rid: str, record: dict) -> None:
    for field in ("name", "owner", "invariant_protected", "invariant_violation_symptom",
                  "why_this_boundary", "miar_stage"):
        _require_str(rid, record, field)
    if record.get("boundary_kind") not in BOUNDARY_KIND_ENUM:
        raise ValueError(f"{rid}: boundary_kind {record.get('boundary_kind')!r} not in {sorted(BOUNDARY_KIND_ENUM)}")
    if record.get("authority_layer") not in AUTHORITY_LAYER_ENUM:
        raise ValueError(f"{rid}: authority_layer {record.get('authority_layer')!r} not in {sorted(AUTHORITY_LAYER_ENUM)}")
    for field in ("members", "members_exclude", "consumers", "concepts", "change_classes",
                  "evidence", "findings"):
        _require_list(rid, record, field)
    if not record["members"]:
        raise ValueError(f"{rid}: members must declare at least one glob or path")
    contract = record.get("contract")
    if not isinstance(contract, dict):
        raise ValueError(f"{rid}: contract must be a mapping")
    for field in _BOUNDARY_INLINE_CONTRACT_REQUIRED:
        if not isinstance(contract.get(field), list):
            raise ValueError(f"{rid}: contract.{field} must be a list")
    # Optional first-class CT references (PR-2)
    if "contract_ids" in record and not isinstance(record.get("contract_ids"), list):
        raise ValueError(f"{rid}: contract_ids must be a list when present")
    for ctid in record.get("contract_ids") or []:
        if not isinstance(ctid, str) or not _ID_RE["contract"].match(ctid):
            raise ValueError(f"{rid}: contract_ids entry {ctid!r} must match CT-NNN")
    for ev in record["evidence"]:
        if not isinstance(ev, dict) or "path" not in ev:
            raise ValueError(f"{rid}: evidence entry missing 'path': {ev!r}")
        if ev.get("type") not in EVIDENCE_TYPE_ENUM:
            raise ValueError(f"{rid}: evidence type {ev.get('type')!r} not in {sorted(EVIDENCE_TYPE_ENUM)}")


def _validate_contract_record(rid: str, record: dict) -> None:
    """First-class CT-* schema (SEMANTIC_OS_V1_DESIGN PR-2)."""
    for field in ("name", "why_this_contract"):
        _require_str(rid, record, field)
    if record.get("contract_kind") not in CONTRACT_KIND_ENUM:
        raise ValueError(
            f"{rid}: contract_kind {record.get('contract_kind')!r} not in {sorted(CONTRACT_KIND_ENUM)}"
        )
    if record.get("authority_layer") not in AUTHORITY_LAYER_ENUM:
        raise ValueError(
            f"{rid}: authority_layer {record.get('authority_layer')!r} not in {sorted(AUTHORITY_LAYER_ENUM)}"
        )
    for field in (
        "governs_concepts",
        "governs_boundaries",
        "inputs",
        "outputs",
        "guarantees",
        "non_guarantees",
        "enforced_by_tests",
        "findings",
    ):
        _require_list(rid, record, field)
    if not record["guarantees"]:
        raise ValueError(f"{rid}: guarantees must declare at least one entry")
    if not record["governs_concepts"] and not record["governs_boundaries"]:
        raise ValueError(
            f"{rid}: must govern at least one concept or boundary "
            f"(governs_concepts / governs_boundaries both empty)"
        )
    for cid in record["governs_concepts"]:
        if not isinstance(cid, str) or not _ID_RE["concept"].match(cid):
            raise ValueError(f"{rid}: governs_concepts entry {cid!r} must match CN-NNN")
    for bid in record["governs_boundaries"]:
        if not isinstance(bid, str) or not _ID_RE["boundary"].match(bid):
            raise ValueError(f"{rid}: governs_boundaries entry {bid!r} must match BD-NNN")
    for test_path in record["enforced_by_tests"]:
        if not isinstance(test_path, str) or not test_path.strip():
            raise ValueError(f"{rid}: enforced_by_tests entries must be non-empty strings")


def _validate_journey(rid: str, record: dict) -> None:
    for field in ("name", "source_doc", "trigger", "why_this_path"):
        _require_str(rid, record, field)
    if record.get("journey_kind") not in JOURNEY_KIND_ENUM:
        raise ValueError(f"{rid}: journey_kind {record.get('journey_kind')!r} not in {sorted(JOURNEY_KIND_ENUM)}")
    for field in ("terminal_outcomes", "steps", "async_feeders"):
        _require_list(rid, record, field)
    for step in record["steps"]:
        if not isinstance(step, dict):
            raise ValueError(f"{rid}: step must be a mapping, got {step!r}")
        missing = [f for f in _STEP_REQUIRED if f not in step]
        if missing:
            raise ValueError(f"{rid}: step {step.get('step_id')!r} missing fields: {missing}")
        sid = step.get("step_id")
        if not isinstance(sid, str) or not _STEP_ID_RE.match(sid):
            raise ValueError(f"{rid}: step_id {sid!r} must match {_STEP_ID_RE.pattern}")
        if not sid.startswith(rid + "."):
            raise ValueError(f"{rid}: step_id {sid!r} must be namespaced under its journey")
        if not isinstance(step.get("order"), int) or step["order"] < 1:
            raise ValueError(f"{rid}: step {sid} order must be a positive int")
        if step.get("on_failure") not in ON_FAILURE_ENUM:
            raise ValueError(f"{rid}: step {sid} on_failure {step.get('on_failure')!r} not in {sorted(ON_FAILURE_ENUM)}")
        if not isinstance(step.get("next"), list):
            raise ValueError(f"{rid}: step {sid} next must be a list")
    for feeder in record["async_feeders"]:
        if not isinstance(feeder, dict) or not feeder.get("name"):
            raise ValueError(f"{rid}: async_feeder entry missing 'name': {feeder!r}")
        if feeder.get("kind") not in FEEDER_KIND_ENUM:
            raise ValueError(f"{rid}: async_feeder kind {feeder.get('kind')!r} not in {sorted(FEEDER_KIND_ENUM)}")


#: Fields that are legitimately DERIVED joins on OTHER kinds (e.g. owner_boundary is required on
#: concepts) so they cannot live in the global _FORBIDDEN_HAND_FIELDS set — but on a file_identity
#: record they are still exact-path joins computed in semantic_objects.py, never hand-authored.
_IDENTITY_ONLY_FORBIDDEN_FIELDS = frozenset({"owner_boundary", "imported_by", "tests_importing"})

#: tier -> (required confidence, required provenance). The four fields (tier / confidence /
#: provenance / derivation) must move together so an auto-vs-curated row is unambiguous.
_IDENTITY_TIER_COHERENCE = {1: ("HIGH", "CURATED"), 2: ("MEDIUM", "CURATED"), 3: ("LOW", "DERIVED")}


def _validate_file_identity(rid: str, record: dict) -> None:
    """Schema for a FileIdentity: ``semantic_id -> semantic_name -> physical_path``.

    Advisory-only rename-stable naming layer. See the module docstring's kind table and
    ``docs/governance/SEMANTIC_FILE_IDENTITY_REPORT.md``. Grants no rename or production
    authority — physical filenames are never touched by this layer (CLAUDE.md §6.5).
    """
    tier = record.get("tier")
    provenance = record.get("provenance")
    is_derived = provenance == "DERIVED"

    for field in ("semantic_name", "physical_path", "filename_status_reason", "summary_50"):
        _require_str(rid, record, field, allow_empty=is_derived)
    for field in ("aliases", "concept_ids", "evidence"):
        _require_list(rid, record, field)

    if tier not in IDENTITY_TIER_ENUM:
        raise ValueError(f"{rid}: tier {tier!r} not in {sorted(IDENTITY_TIER_ENUM)}")
    confidence = record.get("confidence")
    if confidence not in IDENTITY_CONFIDENCE_ENUM:
        raise ValueError(f"{rid}: confidence {confidence!r} not in {sorted(IDENTITY_CONFIDENCE_ENUM)}")
    if provenance not in IDENTITY_PROVENANCE_ENUM:
        raise ValueError(f"{rid}: provenance {provenance!r} not in {sorted(IDENTITY_PROVENANCE_ENUM)}")
    role = record.get("role")
    if role not in IDENTITY_ROLE_ENUM:
        raise ValueError(f"{rid}: role {role!r} not in {sorted(IDENTITY_ROLE_ENUM)}")
    layer = record.get("semantic_layer")
    if layer not in SEMANTIC_LAYER_ENUM:
        raise ValueError(f"{rid}: semantic_layer {layer!r} not in {sorted(SEMANTIC_LAYER_ENUM)}")
    fss = record.get("filename_semantic_status")
    if fss not in FILENAME_SEMANTIC_STATUS_ENUM:
        raise ValueError(
            f"{rid}: filename_semantic_status {fss!r} not in {sorted(FILENAME_SEMANTIC_STATUS_ENUM)}"
        )
    if not isinstance(record.get("canonical"), bool):
        raise ValueError(f"{rid}: canonical must be a bool")

    expect_conf, expect_prov = _IDENTITY_TIER_COHERENCE[tier]
    if confidence != expect_conf or provenance != expect_prov:
        raise ValueError(
            f"{rid}: tier {tier} requires confidence={expect_conf!r} provenance={expect_prov!r} "
            f"(got confidence={confidence!r} provenance={provenance!r})"
        )

    derivation = record.get("derivation")
    if provenance == "CURATED" and derivation is not None:
        raise ValueError(f"{rid}: derivation must be null for CURATED provenance (got {derivation!r})")
    if is_derived:
        if not (isinstance(derivation, str) and derivation.startswith("path_slug/")):
            raise ValueError(
                f"{rid}: derivation must start with 'path_slug/' for DERIVED provenance (got {derivation!r})"
            )
        if record.get("why_this_identity"):
            raise ValueError(f"{rid}: DERIVED rows must carry an empty why_this_identity (unreviewed)")
        if record.get("aliases"):
            raise ValueError(f"{rid}: DERIVED rows must carry empty aliases (no reviewed alias claim)")

    if tier == 1 and fss == "UNKNOWN":
        raise ValueError(f"{rid}: Tier-1 identity may not carry filename_semantic_status UNKNOWN — it must be reviewed")
    if fss not in ("ALIGNED", "UNKNOWN") and not (record.get("filename_status_reason") or "").strip():
        raise ValueError(f"{rid}: filename_semantic_status {fss!r} requires a non-empty filename_status_reason")

    path = record.get("physical_path") or ""
    posix = str(path).replace("\\", "/")
    if not posix.endswith(".py"):
        raise ValueError(f"{rid}: physical_path must end in .py: {path!r}")
    if posix.startswith("tests/"):
        raise ValueError(
            f"{rid}: physical_path may not be under tests/ — file identities cover code, not tests: {path!r}"
        )
    if _resolve_repo_path(posix) is None:
        raise ValueError(f"{rid}: physical_path does not exist on disk: {path!r}")

    if len(record["summary_50"]) > SUMMARY_50_MAX:
        raise ValueError(f"{rid}: summary_50 is {len(record['summary_50'])} chars > {SUMMARY_50_MAX}")

    for cid in record["concept_ids"]:
        if not isinstance(cid, str) or not _ID_RE["concept"].match(cid):
            raise ValueError(f"{rid}: concept_ids entry {cid!r} must match CN-NNN")

    for ev in record["evidence"]:
        if not isinstance(ev, dict) or "path" not in ev:
            raise ValueError(f"{rid}: evidence entry missing 'path': {ev!r}")
        if ev.get("type") not in EVIDENCE_TYPE_ENUM:
            raise ValueError(f"{rid}: evidence type {ev.get('type')!r} not in {sorted(EVIDENCE_TYPE_ENUM)}")

    # C6 — owner_boundary/encyclopedia_id/script_registry_id/imports are DERIVED exact-path
    # joins computed in semantic_objects.py; hand-authoring them here would duplicate (and could
    # silently contradict) that join. owner_boundary is deliberately NOT in the global
    # _FORBIDDEN_HAND_FIELDS (concepts legitimately carry it), so this identity-specific
    # rejection is the only thing that catches the mistake on this kind.
    present = sorted(set(record) & _IDENTITY_ONLY_FORBIDDEN_FIELDS)
    if present:
        raise ValueError(f"{rid}: derived field(s) may not be hand-authored on a file_identity: {present}")
