"""
insight_reporter.py
═══════════════════════════════════════════════════════════════════════════════
Dynamic LLM-powered insight reporting for the CRT trading system.

Replaces static log lines with natural-language narratives generated by the
local inference server (via llama_gate.llm_insight).

Graceful degradation: if the LLM server is unavailable, all functions fall
back to static formatted summaries — identical to what the old logger produced.
The pipeline is NEVER blocked by this module.

─────────────────────────────────────────────────────────────────────────────
USAGE
─────────────────────────────────────────────────────────────────────────────

  from insight_reporter import InsightReporter

  reporter = InsightReporter(symbol="EURUSD", output_dir="reports")

  # After a trade decision:
  reporter.trade_decision(score_result, sub_scores)

  # After a trading session:
  reporter.session_summary(session_name, trades_list, summary_metrics)

  # After model evaluation:
  reporter.eval_report(eval_result, model_type="Gaussian")

  # After a backtest run:
  reporter.backtest_summary(backtest_metrics)

  # On regime change:
  reporter.regime_alert(prev_regime, curr_regime, volatility, session)

  # Save accumulated report to disk:
  reporter.save()

─────────────────────────────────────────────────────────────────────────────
"""

from __future__ import annotations

import logging
import os
from datetime import datetime
from typing import Any, Dict, List, Optional

from llama_gate import llm_insight, _fallback_insight

log = logging.getLogger("InsightReporter")


# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _safe_fmt(value: Any, fmt: str = "") -> Any:
    """Return formatted value or 'N/A' if None."""
    if value is None:
        return "N/A"
    if fmt:
        try:
            return format(value, fmt)
        except (TypeError, ValueError):
            return str(value)
    return value


def _pct(value: Any) -> float:
    """Coerce to float for percentage display."""
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


# ─────────────────────────────────────────────────────────────────────────────
# INSIGHT REPORTER
# ─────────────────────────────────────────────────────────────────────────────

class InsightReporter:
    """
    LLM-powered narrative report generator for the CRT trading system.

    Parameters
    ----------
    symbol     : trading symbol (e.g. "EURUSD")
    output_dir : directory for saved report files (default: "reports")
    enabled    : set False to fully disable LLM calls (uses fallback only)
    verbose    : if True, also print insights to stdout
    """

    def __init__(
        self,
        symbol: str = "UNKNOWN",
        output_dir: str = "reports",
        enabled: bool = True,
        verbose: bool = True,
    ) -> None:
        self.symbol     = symbol
        self.output_dir = output_dir
        self.enabled    = enabled
        self.verbose    = verbose

        self._entries: List[str] = []  # accumulated report lines

        os.makedirs(output_dir, exist_ok=True)

    # ─────────────────────────────────────────────────────────────────────────
    # REPORT FUNCTIONS
    # ─────────────────────────────────────────────────────────────────────────

    def trade_decision(
        self,
        score_result: Dict[str, Any],
        sub_scores: Optional[Dict[str, float]] = None,
    ) -> str:
        """
        Narrate a single trade decision.

        Parameters
        ----------
        score_result : output from ScoringEngine.score() or RRFusionLayer.score()
                       Expected keys: gaussian, decision, reason,
                       plus optional: expected_rr, probability_of_win, final_score
        sub_scores   : optional dict with keys sweep, breakout, retest, time
                       (from scoring_engine.compute_scores())

        Returns
        -------
        str — narrative string (logged + stored)
        """
        sub = sub_scores or {}
        context = {
            "gaussian_score":  _safe_fmt(score_result.get("gaussian", score_result.get("final_score", 0.0))),
            "ml_expected_rr":  _safe_fmt(score_result.get("expected_rr")),
            "ml_win_prob":     _safe_fmt(score_result.get("probability_of_win")),
            "sweep":           _safe_fmt(sub.get("sweep", "N/A")),
            "breakout":        _safe_fmt(sub.get("breakout", "N/A")),
            "retest":          _safe_fmt(sub.get("retest", "N/A")),
            "time":            _safe_fmt(sub.get("time", "N/A")),
            "decision":        score_result.get("decision", "N/A"),
            "reason":          score_result.get("reason", "N/A"),
        }
        narrative = self._generate("trade_decision", context)
        self._record("TRADE", narrative)
        return narrative

    def session_summary(
        self,
        session_name: str,
        trades: Optional[List[Dict]] = None,
        metrics: Optional[Dict[str, Any]] = None,
    ) -> str:
        """
        Narrate a session summary.

        Parameters
        ----------
        session_name : e.g. "LONDON", "NEW_YORK", "ASIA"
        trades       : list of trade result dicts (optional — used to compute
                       win_rate / net_rr if not in metrics)
        metrics      : pre-computed session metrics dict (optional)

        Returns
        -------
        str — narrative string
        """
        m = metrics or {}

        # Derive from trades if not provided
        if trades and not m:
            approved = [t for t in trades if t.get("decision") == "EXECUTE"]
            wins     = [t for t in approved if _pct(t.get("pnl_rr_net", 0)) >= 1.0]
            m = {
                "n_trades":        len(trades),
                "approved_trades": len(approved),
                "win_rate":        len(wins) / len(approved) if approved else 0.0,
                "net_rr":          sum(_pct(t.get("pnl_rr_net", 0)) for t in approved),
                "avg_gaussian":    sum(_pct(t.get("gaussian", 0)) for t in approved) / max(len(approved), 1),
                "avg_ml_rr":       sum(_pct(t.get("expected_rr", 0)) for t in approved) / max(len(approved), 1),
                "max_drawdown":    0.0,
            }

        context = {
            "symbol":           self.symbol,
            "session":          session_name,
            "n_trades":         _safe_fmt(m.get("n_trades")),
            "approved_trades":  _safe_fmt(m.get("approved_trades")),
            "win_rate":         _safe_fmt(m.get("win_rate")),
            "net_rr":           _safe_fmt(m.get("net_rr")),
            "avg_gaussian":     _safe_fmt(m.get("avg_gaussian")),
            "avg_ml_rr":        _safe_fmt(m.get("avg_ml_rr")),
            "max_drawdown":     _safe_fmt(m.get("max_drawdown")),
        }
        narrative = self._generate("session_summary", context)
        self._record("SESSION", narrative)
        return narrative

    def eval_report(
        self,
        eval_result: Any,
        model_type: str = "Model",
    ) -> str:
        """
        Narrate a model evaluation result.

        Parameters
        ----------
        eval_result : GaussianEvalResult or EvalResult dataclass from evaluator.py,
                      OR a plain dict with the same keys.
        model_type  : label for the model type ("Gaussian", "ML", "Fusion", etc.)

        Returns
        -------
        str — narrative string
        """
        def _get(obj, key, default=0.0):
            if isinstance(obj, dict):
                return obj.get(key, default)
            return getattr(obj, key, default)

        context = {
            "model_type":         model_type,
            "n_samples":          _get(eval_result, "n_samples", 0),
            "corr_expected_rr":   _safe_fmt(_get(eval_result, "corr_expected_rr", 0.0)),
            "calibration_error":  _safe_fmt(_get(eval_result, "calibration_error", 0.0)),
            "mean_expected_rr":   _safe_fmt(_get(eval_result, "mean_expected_rr", 0.0)),
            "mean_actual_rr":     _safe_fmt(_get(eval_result, "mean_actual_rr", 0.0)),
            "class_distribution": str(_get(eval_result, "class_distribution", {})),
        }
        narrative = self._generate("eval_report", context)
        self._record("EVAL", narrative)
        return narrative

    def backtest_summary(
        self,
        metrics: Dict[str, Any],
    ) -> str:
        """
        Narrate an overall backtest result.

        Parameters
        ----------
        metrics : dict from backtest run. Expected keys:
                  total_trades, win_rate, expectancy_rr, max_drawdown_pct,
                  sharpe (optional), expansions (optional), retests (optional)

        Returns
        -------
        str — narrative string
        """
        context = {
            "symbol":           self.symbol,
            "total_trades":     _safe_fmt(metrics.get("total_trades", metrics.get("approved_trades"))),
            "win_rate":         _safe_fmt(metrics.get("win_rate")),
            "expectancy_rr":    _safe_fmt(metrics.get("expectancy_rr")),
            "max_drawdown_pct": _safe_fmt(metrics.get("max_drawdown_pct")),
            "sharpe":           _safe_fmt(metrics.get("sharpe")),
            "expansions":       _safe_fmt(metrics.get("expansions")),
            "retests":          _safe_fmt(metrics.get("retests")),
        }
        narrative = self._generate("backtest_summary", context)
        self._record("BACKTEST", narrative)
        return narrative

    def regime_alert(
        self,
        prev_regime: str,
        curr_regime: str,
        volatility: float,
        session: str,
    ) -> str:
        """
        Narrate a regime change event.

        Parameters
        ----------
        prev_regime : previous regime label (e.g. "TRENDING", "RANGING")
        curr_regime : new regime label
        volatility  : current ATR-derived volatility value
        session     : trading session name

        Returns
        -------
        str — narrative string
        """
        context = {
            "symbol":      self.symbol,
            "prev_regime": prev_regime,
            "curr_regime": curr_regime,
            "volatility":  _safe_fmt(volatility),
            "session":     session,
        }
        narrative = self._generate("regime_alert", context)
        self._record("REGIME", narrative)
        return narrative

    # ─────────────────────────────────────────────────────────────────────────
    # SAVE TO FILE
    # ─────────────────────────────────────────────────────────────────────────

    def save(self, filename: Optional[str] = None) -> str:
        """
        Write accumulated report entries to a Markdown file.

        Parameters
        ----------
        filename : override output filename (default: auto-generated)

        Returns
        -------
        str — path to the saved file
        """
        if not self._entries:
            log.info("InsightReporter.save(): no entries to save")
            return ""

        if filename is None:
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = os.path.join(self.output_dir, f"{self.symbol}_{ts}_insight.md")

        header = (
            f"# Trade Insight Report\n"
            f"**Symbol:** {self.symbol}  \n"
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  \n\n"
            f"---\n\n"
        )

        body = "\n\n".join(self._entries)

        with open(filename, "w", encoding="utf-8") as f:
            f.write(header + body + "\n")

        log.info(f"InsightReporter: report saved → {filename}")
        return filename

    def clear(self) -> None:
        """Clear accumulated entries."""
        self._entries.clear()

    # ─────────────────────────────────────────────────────────────────────────
    # INTERNAL
    # ─────────────────────────────────────────────────────────────────────────

    def _generate(self, report_type: str, context: dict) -> str:
        """Call LLM or fallback, return narrative string."""
        if self.enabled:
            narrative = llm_insight(context, report_type)
        else:
            narrative = _fallback_insight(context, report_type)
        return narrative

    def _record(self, tag: str, narrative: str) -> None:
        """Log and accumulate a report entry."""
        ts = datetime.now().strftime("%H:%M:%S")
        log.info(f"[{tag}] {narrative}")
        if self.verbose:
            print(f"\n[InsightReporter | {tag} | {ts}]\n{narrative}\n")
        entry = f"## [{tag}] — {ts}\n\n{narrative}"
        self._entries.append(entry)


# ─────────────────────────────────────────────────────────────────────────────
# MODULE-LEVEL SINGLETON
# ─────────────────────────────────────────────────────────────────────────────

_default_reporter: Optional[InsightReporter] = None


def get_reporter(
    symbol: str = "UNKNOWN",
    output_dir: str = "reports",
    enabled: bool = True,
) -> InsightReporter:
    """
    Get or create the module-level default InsightReporter.

    Useful for simple single-symbol pipelines where one reporter
    should persist for the entire session.

    Usage:
        from insight_reporter import get_reporter
        reporter = get_reporter(symbol="EURUSD")
        reporter.trade_decision(score_result, sub_scores)
    """
    global _default_reporter
    if _default_reporter is None or _default_reporter.symbol != symbol:
        _default_reporter = InsightReporter(
            symbol=symbol,
            output_dir=output_dir,
            enabled=enabled,
        )
    return _default_reporter


# ─────────────────────────────────────────────────────────────────────────────
# STANDALONE TEST
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("InsightReporter — Standalone Test (LLM server optional)")
    print("=" * 60)

    reporter = InsightReporter(symbol="EURUSD_TEST", output_dir="reports", enabled=True)

    # Test 1: trade_decision
    score_result = {
        "gaussian":           0.72,
        "final_score":        0.68,
        "expected_rr":        1.4,
        "probability_of_win": 0.63,
        "decision":           "EXECUTE",
        "reason":             "normal",
    }
    sub_scores = {"sweep": 0.7, "breakout": 0.62, "retest": 0.81, "time": 0.88}
    narrative = reporter.trade_decision(score_result, sub_scores)
    print(f"[TEST 1 — trade_decision]\n{narrative}\n")

    # Test 2: session_summary from metrics
    session_metrics = {
        "n_trades":        12,
        "approved_trades": 8,
        "win_rate":        0.625,
        "net_rr":          3.2,
        "avg_gaussian":    0.74,
        "avg_ml_rr":       1.35,
        "max_drawdown":    0.082,
    }
    narrative = reporter.session_summary("LONDON", metrics=session_metrics)
    print(f"[TEST 2 — session_summary]\n{narrative}\n")

    # Test 3: eval_report from dict
    eval_dict = {
        "n_samples":          450,
        "corr_expected_rr":   0.312,
        "calibration_error":  0.047,
        "mean_expected_rr":   1.21,
        "mean_actual_rr":     1.15,
        "class_distribution": {"class_0": 120, "class_1": 180, "class_2": 100, "class_3": 50},
    }
    narrative = reporter.eval_report(eval_dict, model_type="Gaussian")
    print(f"[TEST 3 — eval_report]\n{narrative}\n")

    # Test 4: backtest_summary
    backtest_metrics = {
        "total_trades":     210,
        "win_rate":         0.587,
        "expectancy_rr":    1.42,
        "max_drawdown_pct": 0.093,
        "sharpe":           1.8,
        "expansions":       180,
        "retests":          142,
    }
    narrative = reporter.backtest_summary(backtest_metrics)
    print(f"[TEST 4 — backtest_summary]\n{narrative}\n")

    # Test 5: regime_alert
    narrative = reporter.regime_alert("RANGING", "TRENDING", 0.0024, "LONDON")
    print(f"[TEST 5 — regime_alert]\n{narrative}\n")

    # Save report
    path = reporter.save()
    print(f"\nReport saved to: {path}")
    print("\nAll tests completed.")