import json
import sys
from pathlib import Path

import pytest

# Tests for inout.config / inout.probability_engine are skipped until those
# modules ship (inout/runner.py is not yet in the main branch).
collect_ignore = [
    "inout/test_inout-1.py",
    "inout/test_probability_engine.py",
]

# Add src/ to sys.path so all packages resolve without a 'src.' prefix
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))


def pytest_addoption(parser):
    parser.addoption(
        "--run-measurement", action="store_true", default=False,
        help="run @pytest.mark.measurement tests (they read gitignored results/ evidence)",
    )


def pytest_collection_modifyitems(config, items):
    """Measurement tests are owner-run on demand (edge-research-platform-testing-plan.md §2/§9).

    They read evidence under gitignored results/, which only exists on the machine that ran the
    study, so by default they SKIP with a reason instead of failing. Opt in with
    `--run-measurement` or by selecting them: `pytest -m measurement`.
    """
    if config.getoption("--run-measurement") or "measurement" in (config.getoption("-m") or ""):
        return
    skip = pytest.mark.skip(reason="measurement test: needs results/ evidence; run with --run-measurement")
    for item in items:
        if item.get_closest_marker("measurement") is not None:
            item.add_marker(skip)


@pytest.fixture(scope="session", autouse=True)
def _declare_synthetic_corpus_clocks(tmp_path_factory):
    """Phase-3 clock provenance for test-built corpora.

    `ohlcv_schema.require_reviewed_clock` refuses to read any OHLCV file whose timezone has not
    been human-reviewed (see data_ingestion/clock_registry.py). That gate is about corpora that
    ARRIVE from outside with an unknown clock — it is not about a 6-row CSV a test writes into
    tmp_path and deletes on teardown, whose clock the test itself chose.

    So the harness declares its own scratch tree, in process, once. This is a CALL in test
    infrastructure — not an env var, not a config flag, and never persisted to the registry — and
    `test_ohlcv_clock_provenance.py::test_no_production_module_declares_in_process` fails the build
    if any module under `src/` tries the same trick.
    """
    from data_ingestion.clock_registry import declare_tree_in_process
    declare_tree_in_process(
        tmp_path_factory.getbasetemp(), "UTC",
        reason="pytest tmp tree: corpora are constructed by the test that reads them",
    )


@pytest.fixture(scope="session", autouse=True)
def _mock_unreviewed_real_corpus_clocks():
    """Mock clock for REAL corpora that tests read but a human has not reviewed yet.

    Tests that replay data/BNBUSDT_M15.csv or data/mt5/EURUSD_*.csv check determinism and parity
    (run A == run B), not which clock the stamps are on. Blocking them on the human review would
    make the suite wait on a governance decision it is not testing. So the harness mocks the clock
    in process, by acquisition family: crypto USDT pairs are exchange UTC, data/mt5/ is broker time.

    Scope is deliberately narrow:
      - only registry records with user_reviewed=false (reviewed records keep the real SHA check);
      - never persisted — configs/data_provenance/ohlcv_clock_registry.json is untouched, and
        production still refuses these files until the review CLI is run;
      - test_ohlcv_clock_provenance.py isolates itself from in-process declarations, so the gate
        itself is still tested for real.
    """
    from data_ingestion import clock_registry as cr

    root = cr.repo_root()
    for key, rec in cr.load_registry().items():
        if rec.user_reviewed or not key.endswith(".csv"):
            continue
        name = Path(key).name.upper()
        if key.startswith("data/mt5/"):
            tz = cr.TZ_MT5_SERVER_NY_DST
        elif "USDT" in name:
            tz = cr.TZ_UTC
        else:
            continue
        cr.declare_in_process(root / key, tz,
                              reason="pytest mock clock: unreviewed real corpus, not a review")


_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "test_vectors.json"


@pytest.fixture(scope="session")
def canonical_vectors():
    """200 deterministic seed-42 synthetic 35-dim feature records.

    Generated by scripts/data/generate_vectors.py.
    Re-run that script whenever CANONICAL_FEATURE_ORDER changes.
    """
    assert _FIXTURE_PATH.exists(), (
        f"Fixture missing: {_FIXTURE_PATH}\n"
        "Run: python scripts/data/generate_vectors.py"
    )
    return json.loads(_FIXTURE_PATH.read_text())
