import json
import sys
from pathlib import Path

import pytest

# Add src/ to sys.path so all packages resolve without a 'src.' prefix
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "test_vectors.json"


@pytest.fixture(scope="session")
def canonical_vectors():
    """200 deterministic seed-42 synthetic 35-dim feature records.

    Generated by scripts/data/generate_vectors.py.
    Re-run that script whenever CANONICAL_FEATURE_ORDER changes.
    """
    assert _FIXTURE_PATH.exists(), (
        f"Fixture missing: {_FIXTURE_PATH}\n"
        "Run: python scripts/data/generate_vectors.py"
    )
    return json.loads(_FIXTURE_PATH.read_text())
