"""Guard for asset_coverage_v1 (STORY-12.3 / P0).

Registered writers must exist. Census writers must be registered or on the
shrink-only UNREGISTERED pin. Never hand-edit data/asset_coverage.jsonl.
"""
from __future__ import annotations

import ast
import json
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts" / "analysis"))

from asset_writer_census import census  # noqa: E402


@pytest.fixture(scope="module", autouse=True)
def _seed_registry() -> None:
    """data/asset_coverage.jsonl is generated. Reseed before the asserts."""
    subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "governance" / "seed_asset_coverage.py")],
        check=True,
        cwd=ROOT,
    )


REGISTRY = ROOT / "data" / "asset_coverage.jsonl"
# Shrink-only pin. data/ is LOCAL_BLOB (/data/*), so the committed pin lives with the other
# governance pins. The registry itself is generated by the seed (PRIMARY -> GENERATED).
PIN = ROOT / "docs" / "governance" / "asset_coverage_unregistered.json"
FINDINGS = ROOT / "docs" / "current-findings.md"
PINNED_REGISTERED = 8

RAILS = {"backtest", "paper_live", "live", "research", "training", "governance", "control_plane", "ui", "agent"}
FORMATS = {"jsonl", "csv", "parquet", "json", "md", "html", "png", "log"}
GRAINS = {"job", "run", "bar", "bar_layer", "event", "trade", "episode", "aggregate", "static"}
JOINS = {"JOINABLE_RECORDED", "JOINABLE_DERIVED", "RUN_ONLY", "UNJOINABLE", "NOT_EMITTED"}
GAPS = {"NO_RUN_ID", "NO_BAR_TS", "WALL_CLOCK_NOT_BAR_TS", "MULTI_RUN_FILE", "LOCAL_CLOCK_ID", "INDEX_OFFSET", "HOMONYM", "NO_EMIT_SITE", "SILENT_CONDITIONAL"}
BAR_BASIS = {"bar_open_ts", "csv_row", "csv_row_plus_1", "engine_counter", "wall_clock", "none"}


def _rows():
    return [json.loads(l) for l in REGISTRY.read_text(encoding="utf-8").splitlines() if l.strip()]


def _module_file(module: str) -> Path:
    rel = Path(*module.split(".")).with_suffix(".py")
    src = ROOT / "src" / rel
    if src.is_file():
        return src
    scripts = ROOT / rel
    if scripts.is_file():
        return scripts
    raise FileNotFoundError(module)


def _symbols(path: Path) -> set[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    return {n.name for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))}


def test_registered_count_ratchet():
    rows = _rows()
    assert len(rows) >= PINNED_REGISTERED
    assert [r["id"] for r in rows] == [f"RTC-{i:03d}" for i in range(1, len(rows) + 1)]


def test_enums_and_symbols():
    findings = FINDINGS.read_text(encoding="utf-8")
    for row in _rows():
        assert row["rail"] in RAILS
        assert row["format"] in FORMATS
        assert row["grain"] in GRAINS
        assert row["join_status"] in JOINS
        for g in row["gaps"]:
            assert g in GAPS
        if row["bar_key"] is not None:
            assert row["bar_key"]["basis"] in BAR_BASIS
        path = _module_file(row["module"])
        assert row["writer_symbol"] in _symbols(path)
        for fid in row["findings"]:
            assert f"### {fid}" in findings or f"### {fid} " in findings
        for ev in row["evidence"]:
            tracked = subprocess.run(
                ["git", "ls-files", "--", ev["path"]],
                cwd=ROOT, capture_output=True, text=True, check=True,
            ).stdout.strip()
            assert tracked, ev["path"]


def test_census_writers_registered_or_pinned():
    registered = {f"{r['module']}|{r['writer_symbol']}" for r in _rows()}
    found = {f"{r['module']}|{r['writer_symbol']}" for r in census()}
    pin = set(json.loads(PIN.read_text(encoding="utf-8")))
    assert pin.isdisjoint(registered)
    assert found - registered == pin
