"""Generate reports/framework_registry_report.md from the registry (001 §M2 Deliverable 2).

Deterministic / byte-stable: no wall-clock timestamps — every value is derived from the registry
+ findings doc, so reruns produce identical output (committable + diffable).

    python scripts/governance/framework_registry_report.py
"""
from __future__ import annotations

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
for _p in (_ROOT / "src", _ROOT / "scripts"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from governance.framework_registry import FrameworkRegistry, valid_finding_ids  # noqa: E402

REGISTRY = _ROOT / "data" / "framework_registry.jsonl"
OUT = _ROOT / "reports" / "framework_registry_report.md"

_LEVEL_NAMES = {
    0: "Kernel", 1: "Domain", 2: "Style", 3: "Strategy",
    4: "Intelligence/AI", 5: "Risk", 6: "Execution",
}
_STATUSES = ["extant", "implicit", "dormant", "orphaned", "stub", "planned", "killed"]


def _summary_matrix(reg: FrameworkRegistry) -> list[str]:
    lines = ["## 1. Summary — count per level × status", "",
             "| Level | " + " | ".join(_STATUSES) + " | total |",
             "|---|" + "---|" * (len(_STATUSES) + 1)]
    for lvl in range(0, 7):
        recs = reg.filter(level=lvl)
        cells = [str(sum(1 for r in recs if r["status"] == s)) for s in _STATUSES]
        lines.append(f"| {lvl} {_LEVEL_NAMES[lvl]} | " + " | ".join(cells) + f" | {len(recs)} |")
    lines.append(f"| **all** | " + " | ".join(
        str(sum(1 for r in reg.records if r["status"] == s)) for s in _STATUSES
    ) + f" | **{len(reg.records)}** |")
    return lines + [""]


def _gap_analysis(reg: FrameworkRegistry) -> list[str]:
    lines = ["## 2. Gap analysis — empty or non-extant levels", ""]
    for lvl in range(0, 7):
        recs = reg.filter(level=lvl)
        if not recs:
            lines.append(f"- **L{lvl} {_LEVEL_NAMES[lvl]}**: EMPTY — no registered component.")
            continue
        non_extant = [r for r in recs if r["status"] != "extant"]
        if non_extant:
            tag = ", ".join(f"{r['id']}({r['status']})" for r in non_extant)
            lines.append(f"- **L{lvl} {_LEVEL_NAMES[lvl]}**: {len(non_extant)}/{len(recs)} not extant — {tag}")
    return lines + [""]


def _orphan_report(reg: FrameworkRegistry) -> list[str]:
    lines = ["## 3. Structural orphans (no parent and no children)", "",
             "> Distinct from `status: orphaned` (runtime wiring). These are disconnected tree nodes.", ""]
    orphans = reg.get_orphaned()
    if not orphans:
        lines.append("- none")
    for r in orphans:
        lines.append(f"- {r['id']} · {r['name']} (L{r['level']} {r['type']}, status={r['status']})")
    return lines + [""]


def _finding_coverage(reg: FrameworkRegistry) -> list[str]:
    lines = ["## 4. Finding coverage", ""]
    linked: dict[str, list[str]] = {}
    for r in reg.records:
        for fid in r.get("findings") or []:
            linked.setdefault(fid, []).append(r["id"])
    all_findings = valid_finding_ids()
    unlinked = sorted(all_findings - set(linked))
    lines.append(f"- findings linked to ≥1 component: **{len(linked)}** / {len(all_findings)} total")
    for fid in sorted(linked):
        lines.append(f"  - {fid} → {', '.join(sorted(linked[fid]))}")
    lines.append(f"- findings with **no** linked component ({len(unlinked)}): {', '.join(unlinked) or '—'}")
    return lines + [""]


def _evidence_health(reg: FrameworkRegistry) -> list[str]:
    errs = reg.validate_evidence()
    total = sum(len(r.get("evidence") or []) for r in reg.records)
    lines = ["## 5. Evidence health", "",
             f"- evidence entries: **{total}**, broken: **{len(errs)}**"]
    for e in errs:
        lines.append(f"  - {e}")
    find_errs = reg.validate_findings()
    link_errs = reg.validate_links()
    lines.append(f"- finding-link errors: **{len(find_errs)}**, dangling parent/child: **{len(link_errs)}**")
    for e in find_errs + link_errs:
        lines.append(f"  - {e}")
    return lines + [""]


def _tree(reg: FrameworkRegistry) -> list[str]:
    lines = ["## 6. Hierarchy", "", "```"]

    def walk(node: dict, depth: int) -> None:
        lines.append("  " * depth + f"{node.get('id')} · {node.get('name', '?')} ({node.get('status', '?')})")
        for k in node.get("children", []):
            walk(k, depth + 1)

    roots = sorted((r for r in reg.records if not r.get("parent")), key=lambda r: r["id"])
    for root in roots:
        walk(reg.get_tree(root["id"]), 0)
    lines.append("```")
    return lines + [""]


def build_report(reg: FrameworkRegistry) -> str:
    out = ["# Framework Registry Report", "",
           "> Auto-generated by `scripts/governance/framework_registry_report.py` from "
           "`data/framework_registry.jsonl`. Deterministic — do not hand-edit; re-run the generator.", ""]
    out += _summary_matrix(reg)
    out += _gap_analysis(reg)
    out += _orphan_report(reg)
    out += _finding_coverage(reg)
    out += _evidence_health(reg)
    out += _tree(reg)
    return "\n".join(out) + "\n"


def main() -> int:
    reg = FrameworkRegistry()
    reg.load(REGISTRY)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build_report(reg), encoding="utf-8")
    print(f"wrote {OUT.relative_to(_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
