"""Generate reports/framework_gap_audit.md (001_FRAMEWORK_REGISTRY.md §M3).

Compares the registry against the ideal framework hierarchy and emits per-level gap tables +
a prioritized action list. Deterministic (no wall-clock). Gap text is derived from each record's
verified status + notes, NOT transcribed from the framework docs — so the known DOC_DRIFT
(UltronRiskGate "disabled") does not propagate (CLAUDE.md §6.2).

    python scripts/governance/framework_gap_audit.py
"""
from __future__ import annotations

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
for _p in (_ROOT / "src", _ROOT / "scripts"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from governance.framework_registry import FrameworkRegistry  # noqa: E402

REGISTRY = _ROOT / "data" / "framework_registry.jsonl"
OUT = _ROOT / "reports" / "framework_gap_audit.md"

_LEVEL_NAMES = {
    0: "Universal Kernel", 1: "Domain", 2: "Style", 3: "Strategy",
    4: "Intelligence/AI", 5: "Risk", 6: "Execution",
}

# Domains named in the framework but ABSENT from code (no registry record) — reported, not seeded.
_ABSENT_DOMAINS = ["CryptoFutures", "Equities", "Futures", "Options"]

# Curated, evidence-anchored priority list. Each row reflects VERIFIED status (see notes).
# (priority, gap, effort, impact)
_PRIORITIES = [
    ("P0", "CRT/RR/Gaussian/Zone are mandatory engines, not strategy plugins — STRAT-001 is a "
           "ReactionBased strategy by the hierarchy", "High", "Architecture inversion (F-021)"),
    ("P0", "No Domain class — calendar/cost/leverage implicit in config+scripts (DOMAIN-001/002)",
     "Medium", "Blocks multi-domain expansion"),
    ("P1", "Style layer does not exist — 8 styles are flat under the kernel (STYLE-001..008)",
     "Medium", "Blocks style-constrained selection"),
    ("P1", "config_integrity (INTENT-002) gates nothing at runtime — orphaned",
     "Low", "Governance gap (F-006)"),
    ("P2", "Live execution path unverified; no slippage model (EXEC-002 stub, fixed 12bps)",
     "Medium", "Live PnL unverified (F-010)"),
    ("P2", "Concept drift detected (IMPL-009) but not acted on — no block/size-down",
     "Low", "Risk not enforced (F-008)"),
    ("P3", "RegimeClassifier (IMPL-008) dormant — cognitive/ is sidecar-only",
     "Low", "No regime adaptation (F-012)"),
    ("P4", "PortfolioAllocator (RISK-002) orphaned — not wired into the spine",
     "Low", "Portfolio risk unused (F-013)"),
]

# Explicit correction: the 001 template listed this as a P1 gap. It is FALSE.
_RETRACTED = (
    "**RETRACTED (DOC_DRIFT):** 001's template lists *\"P1 · UltronRiskGate disabled in active "
    "config\"*. CODE-VERIFIED FALSE — RISK-001 has `disabled=false` in `v2_multi_2026_04.json` "
    "and is wired in `live_engine_hook.py`. The gate is ENABLED and live; not a gap."
)


def _level_table(reg: FrameworkRegistry, lvl: int) -> list[str]:
    lines = [f"## Level {lvl}: {_LEVEL_NAMES[lvl]}", "",
             "| Component | Status | Code evidence | Gap |", "|---|---|---|---|"]
    recs = reg.filter(level=lvl)
    # intents are meta — surface them at L0 for governance visibility
    if lvl == 0:
        recs = recs + [r for r in reg.records if r["type"] == "intent" and r not in recs]
    for r in sorted(recs, key=lambda x: x["id"]):
        ev = r["evidence"][0]["path"] if r.get("evidence") else "—"
        gap = "OK" if r["status"] == "extant" and not r.get("notes") else (r.get("notes") or r["status"])
        gap = gap.replace("\n", " ")
        lines.append(f"| {r['id']} {r['name']} | {r['status']} | `{ev}` | {gap} |")
    if lvl == 1:
        for d in _ABSENT_DOMAINS:
            lines.append(f"| {d} | absent | — | Not supported — no registry record |")
    return lines + [""]


def build_audit(reg: FrameworkRegistry) -> str:
    out = ["# Framework Gap Audit", "",
           "> Auto-generated by `scripts/governance/framework_gap_audit.py` from "
           "`data/framework_registry.jsonl`. Status is code-verified; do not hand-edit.", "",
           _RETRACTED, ""]
    for lvl in range(0, 7):
        out += _level_table(reg, lvl)
    out += ["## Prioritized action list", "",
            "> Acting on any row is a SEPARATE, evidence-gated decision (CLAUDE.md §6.5 Authority "
            "Ladder) — the registry surfaces gaps, it grants no authority to change behavior.", "",
            "| Priority | Gap | Effort | Impact |", "|---|---|---|---|"]
    for pri, gap, effort, impact in _PRIORITIES:
        out.append(f"| {pri} | {gap} | {effort} | {impact} |")
    out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    reg = FrameworkRegistry()
    reg.load(REGISTRY)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build_audit(reg), encoding="utf-8")
    print(f"wrote {OUT.relative_to(_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
