#!/usr/bin/env python3
"""seed_semantic_os.py — compile the hand-authored Semantic OS YAMLs into the JSONL projection.

PRIMARY truth is the three hand-authored YAMLs under ``docs/governance/semantic_os/`` (tracked).
This script writes the GENERATED projection under ``data/semantic_os/`` (gitignored, disposable) —
never hand-edit it, regenerate it.

Deterministic by construction (mirrors ``seed_framework_registry.py``): timestamps are PINNED, all
records are sorted by id, keys are sorted. Reruns are byte-identical, which is what
``tests/test_semantic_os.py::test_seed_is_byte_identical_on_rerun`` pins.

Usage:
    python scripts/governance/seed_semantic_os.py
    python scripts/governance/seed_semantic_os.py --objects      # + the generated Object layer
    python scripts/governance/seed_semantic_os.py --check        # validate only, write nothing
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
for _p in (_ROOT / "src", _ROOT / "scripts"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # Windows cp1252 console guard

from governance.semantic_os import (  # noqa: E402
    AUTHORITY,
    SCHEMA_VERSION,
    SemanticOSRegistry,
)

#: Pinned for byte-stable reruns — never `datetime.now()` (that would make every seed a diff).
_TS = "2026-08-08T00:00:00Z"

_SOURCE_DIR = _ROOT / "docs" / "governance" / "semantic_os"
_OUT_DIR = _ROOT / "data" / "semantic_os"


def _stamp(record: dict) -> dict:
    """Attach the computed (C) fields the YAML deliberately does not carry."""
    out = dict(record)
    out["created"] = _TS
    out["last_validated"] = _TS
    out["schema_version"] = SCHEMA_VERSION
    out["authority"] = AUTHORITY  # pinned literal — §6.5, never inherited from the YAML
    return out


def build_records(directory: Path = _SOURCE_DIR) -> dict[str, list[dict]]:
    reg = SemanticOSRegistry.load(directory)

    # file_identities = curated (Tier 1/2, hand-authored) ∪ Tier-3 (machine-derived path slugs
    # for every remaining code-universe path). Tier 3 is never materialized in the YAML — see
    # src/governance/semantic_identity.py's module docstring for why.
    from governance.semantic_identity import derive_tier3_identities
    from governance.semantic_objects import discover_universe

    curated_identities = reg.file_identities
    derived_identities = derive_tier3_identities(discover_universe("code"), curated_identities)
    identities = sorted(
        [*curated_identities.values(), *derived_identities], key=lambda r: r["id"]
    )

    return {
        "concepts": [_stamp(r) for r in sorted(reg.concepts.values(), key=lambda r: r["id"])],
        "boundaries": [_stamp(r) for r in sorted(reg.boundaries.values(), key=lambda r: r["id"])],
        "journeys": [_stamp(r) for r in sorted(reg.journeys.values(), key=lambda r: r["id"])],
        "contracts": [_stamp(r) for r in sorted(reg.contracts.values(), key=lambda r: r["id"])],
        "file_identities": [_stamp(r) for r in identities],
    }


def _write_meta(out_dir: Path, counts: dict[str, int], extra: dict | None = None) -> None:
    meta = {
        "_doc": "GENERATED by scripts/governance/seed_semantic_os.py — do not hand-edit.",
        "schema_version": SCHEMA_VERSION,
        "authority": AUTHORITY,
        "generated_at_utc": _TS,
        "source_dir": "docs/governance/semantic_os",
        "counts": counts,
    }
    if extra:
        meta.update(extra)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "index_meta.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Seed the Semantic OS JSONL projection.")
    parser.add_argument("--source", default=str(_SOURCE_DIR), help="hand-authored YAML directory")
    parser.add_argument("--out", default=str(_OUT_DIR), help="output directory for the projection")
    parser.add_argument("--objects", action="store_true", help="also build the generated Object layer")
    parser.add_argument("--universe", default="code", choices=("code", "all"),
                        help="object universe: 'code' = src+scripts+root, 'all' adds tests")
    parser.add_argument("--check", action="store_true", help="validate only; write nothing")
    args = parser.parse_args(argv)

    source = Path(args.source)
    out_dir = Path(args.out)

    reg = SemanticOSRegistry.load(source)
    errors = reg.validate_all()
    if errors:
        print(f"SEMANTIC OS: INVALID — {len(errors)} error(s)")
        for err in errors:
            print(f"  {err}")
        return 1

    records = build_records(source)
    counts = {key: len(values) for key, values in records.items()}

    if args.check:
        print(f"SEMANTIC OS: VALID — {counts}")
        return 0

    for key, values in records.items():
        SemanticOSRegistry.dump(out_dir / f"{key}.jsonl", values)

    extra: dict = {}
    if args.objects:
        from governance.semantic_objects import build_objects, coverage_report  # lazy: Phase 2

        objects = build_objects(universe=args.universe, generated_at=_TS)
        path = out_dir / "objects.jsonl"
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8", newline="\n") as fh:
            for obj in objects:
                fh.write(json.dumps(obj, ensure_ascii=False, sort_keys=True) + "\n")
        counts["objects"] = len(objects)
        extra["object_universe"] = args.universe
        extra["coverage_gaps"] = coverage_report(objects)

    _write_meta(out_dir, counts, extra)
    print(f"SEMANTIC OS: seeded {counts} -> {out_dir.relative_to(_ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
