"""
_crt_state_generated.py -- GENERATED FILE, DO NOT EDIT BY HAND.

Generated by scripts/maintenance/gen_crt_state_identity.py from active_models.yaml
(crt.runtime.state_list / valid_transitions / parent_timeframe_states).

Re-exported by config_layer.state_identity, which is the module every consumer should import
from and which carries the governance rationale for these definitions. Nothing else should
import this module directly.

To change any of these: edit active_models.yaml, then re-run the generator. Editing this file
by hand is caught by `gen_crt_state_identity.py --check` and by
tests/test_crt_state_generated_parity.py.
"""
from __future__ import annotations

from enum import Enum, auto

__all__ = [
    "CRTState",
    "VALID_TRANSITIONS",
    "PARENT_TIMEFRAME_STATES",
    "EXECUTION_TIMEFRAME_STATES",
]


class CRTState(Enum):
    """Legal states in the CRT state machine.

    Members and their ORDER come from active_models.yaml crt.runtime.state_list. Order is
    load-bearing: values are `auto()` (1..N by declaration order) and reach user-visible
    strings via `.value`, so reordering state_list silently renumbers them. The full
    name->value map is pinned by tests/test_crt_state_generated_parity.py.
    """
    RANGE           = auto()
    SHADOW_PENDING  = auto()
    SWEEP           = auto()
    DISPLACEMENT    = auto()
    EXPANSION       = auto()
    EXPIRED         = auto()
    RETEST          = auto()
    EXECUTION       = auto()
    RESOLUTION      = auto()
    RANGE_C1        = auto()
    MANIPULATION_C2 = auto()
    DISTRIBUTION_C3 = auto()


VALID_TRANSITIONS: dict[CRTState, list[CRTState]] = {
    CRTState.RANGE:           [CRTState.SWEEP, CRTState.SHADOW_PENDING],
    CRTState.SHADOW_PENDING:  [CRTState.SWEEP, CRTState.RANGE],
    CRTState.SWEEP:           [CRTState.DISPLACEMENT, CRTState.EXPANSION, CRTState.RANGE],
    CRTState.DISPLACEMENT:    [CRTState.EXPANSION, CRTState.RANGE],
    CRTState.EXPANSION:       [CRTState.RETEST, CRTState.EXPIRED, CRTState.RANGE],
    CRTState.EXPIRED:         [CRTState.RANGE],
    CRTState.RETEST:          [CRTState.EXECUTION, CRTState.RANGE],
    CRTState.EXECUTION:       [CRTState.RESOLUTION],
    CRTState.RESOLUTION:      [CRTState.RANGE],
    CRTState.RANGE_C1:        [CRTState.MANIPULATION_C2, CRTState.RANGE_C1],
    CRTState.MANIPULATION_C2: [CRTState.DISTRIBUTION_C3, CRTState.RANGE_C1],
    CRTState.DISTRIBUTION_C3: [CRTState.RANGE_C1],
}


PARENT_TIMEFRAME_STATES: frozenset[CRTState] = frozenset({
    CRTState.RANGE_C1,
    CRTState.MANIPULATION_C2,
    CRTState.DISTRIBUTION_C3,
})

# Derived complement -- deliberately NOT declared in the ontology, so the split has
# exactly one authored record (the parent list) and cannot self-disagree.
EXECUTION_TIMEFRAME_STATES: frozenset[CRTState] = frozenset(CRTState) - PARENT_TIMEFRAME_STATES
