#!/usr/bin/env python
"""gen_bridge_layer.py — generate the Bridge Layer specification artifacts.

WHAT THIS IS
------------
A BRIDGE, not a trading-education layer. It maps trading VOCABULARY onto the repository's
existing measurement authorities, end to end:

    OHLCV -> Feature Ontology -> State Ontology -> Decision Ontology -> Measurement Ontology

Every fact in the emitted artifacts is READ FROM THE LIVE AUTHORITIES at generation time
(feature_schema, the ontology YAML, the CRT state identity YAML). Nothing is transcribed by
hand, so the bridge cannot drift from the code it describes.

SOURCE AUTHORITIES (never modified by this script)
--------------------------------------------------
  src/features/feature_schema.py              CANONICAL_FEATURES, _FM_ID_TO_NAME, hashes
  src/features/feature_states.py              FeatureStateEncoder (state ontology)
  configs/formulas/market_ontology.yaml       sections, categories, impl, states
  configs/formulas/crt_state_identity.yaml    CRT state identities
  configs/formulas/market_crt_states.yaml     resolver predicates

OUTPUTS
-------
  bridge_layer/README.md
  bridge_layer/CANONICAL_FEATURES.html
  bridge_layer/concepts.yaml
  bridge_layer/feature_schema.bridge.md
  bridge_layer/state_ontology.md
  bridge_layer/crt_engine_v2_concept_map.md
  bridge_layer/crt_state_resolver_bridge.md

USAGE
-----
    python scripts/analysis/gen_bridge_layer.py            # write
    python scripts/analysis/gen_bridge_layer.py --check    # validate only, no writes

Generated files must not be hand-edited.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC = REPO_ROOT / "src"
OUT = REPO_ROOT / "bridge_layer"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

MARKER_BEGIN = ("<!-- === BRIDGE LAYER: BEGIN "
                "(generated by scripts/analysis/gen_bridge_layer.py) === -->")
MARKER_END = "<!-- === BRIDGE LAYER: END === -->"


# ----------------------------- authority readers -----------------------------

def _load_yaml(path: Path) -> dict:
    import yaml
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def read_schema() -> dict:
    """Live feature schema facts — the Measurement Ontology anchor."""
    from features.feature_schema import (
        CANONICAL_FEATURES, CANONICAL_FEATURE_DIM, _FM_ID_TO_NAME,
        SCHEMA_HASH, FEATURE_ORDER_HASH,
    )
    return {
        "dim": int(CANONICAL_FEATURE_DIM),
        "features": list(CANONICAL_FEATURES),
        "fm_to_name": dict(_FM_ID_TO_NAME),
        "name_to_fm": {v: k for k, v in _FM_ID_TO_NAME.items()},
        "schema_hash": SCHEMA_HASH,
        "order_hash": FEATURE_ORDER_HASH,
    }

def read_ontology() -> dict:
    """Per-feature ontology metadata: section, id, category, impl, states."""
    from features.registry import _ITERATED_SECTIONS
    doc = _load_yaml(REPO_ROOT / "configs" / "formulas" / "market_ontology.yaml")
    rows: dict = {}
    for section in _ITERATED_SECTIONS:
        for name, spec in (doc.get(section) or {}).items():
            if not isinstance(spec, dict):
                continue
            lin = spec.get("lineage") or {}
            vi = lin.get("vector_index")
            tax = spec.get("taxonomy") or {}
            impl = spec.get("impl")
            if isinstance(impl, dict):
                impl = impl.get("callable") or json.dumps(impl)
            rows[name] = {
                "section": section,
                "fm_id": spec.get("id"),
                "category": tax.get("category"),
                "knowledge_class": tax.get("knowledge_class"),
                "impl": impl or spec.get("produced_by"),
                "lifecycle": spec.get("lifecycle"),
                "vector_index": vi if isinstance(vi, int) else None,
                "has_states": bool(spec.get("states")),
                "is_vector_bound": isinstance(vi, int),
            }
    return {"iterated_sections": list(_ITERATED_SECTIONS), "entries": rows}


def read_states() -> dict:
    """State Ontology: vector-bound + non-vector stateful identities."""
    from features.feature_states import FeatureStateEncoder
    enc = FeatureStateEncoder()
    specs = {}
    for name in enc.stateful_features:
        sf = enc.spec(name)
        specs[name] = {
            "fm_id": sf.fm_id,
            "vector_index": sf.vector_index,
            "category": sf.category,
            "state_map": {str(k): v for k, v in sf.value_to_state.items()},
        }
    return {
        "vector_bound": list(enc.vector_bound_features),
        "all_stateful": list(enc.stateful_features),
        "continuous": list(enc.continuous_features),
        "specs": specs,
    }

def read_crt_identity() -> dict:
    """Decision Ontology: CRT state identities + constructor capabilities."""
    doc = _load_yaml(REPO_ROOT / "configs" / "formulas" / "crt_state_identity.yaml")
    ident = doc["identity"]
    states = {}
    for name, spec in (ident.get("states") or {}).items():
        states[name] = {
            "id": spec.get("id"),
            "subgraph": spec.get("subgraph"),
            "occupancy_class": spec.get("occupancy_class"),
            "timeframe_role": spec.get("timeframe_role"),
            "is_ground": spec.get("is_ground"),
            "requires_memory": spec.get("requires_memory"),
            "can_emit_bias": spec.get("can_emit_bias"),
            "can_emit_signal": spec.get("can_emit_signal"),
            "knowledge_status": spec.get("knowledge_status"),
            "lifecycle": spec.get("lifecycle"),
            "description": (spec.get("description") or "").strip(),
            "notes": (spec.get("notes") or "").strip(),
        }
    constructors = {}
    for cname, cspec in (ident.get("constructors") or {}).items():
        caps = cspec.get("capabilities") or {}
        gaps = []
        for g in (caps.get("blocking_gaps") or []):
            if isinstance(g, dict):
                gaps.append({"id": g.get("id"), "capability": g.get("capability"),
                             "summary": g.get("summary")})
            else:
                gaps.append({"id": None, "capability": None, "summary": str(g)})
        constructors[cname] = {
            "description": (cspec.get("description") or "").strip(),
            "capabilities": {
                "runtime_eligible": caps.get("runtime_eligible"),
                "reaches_signal_state": caps.get("reaches_signal_state"),
                "produces_trade_geometry": caps.get("produces_trade_geometry"),
                "produces_occupancy": caps.get("produces_occupancy"),
                "produces_memory": caps.get("produces_memory"),
                "covers_states": list(caps.get("covers_states") or []),
                "blocking_gaps": gaps,
            },
            "state_status": {k: {"reachable": v.get("reachable"),
                                 "defined": v.get("defined"),
                                 "unreachable_reason": v.get("unreachable_reason"),
                                 "construction_diverges_from_engine":
                                     v.get("construction_diverges_from_engine")}
                             for k, v in (cspec.get("states") or {}).items()},
        }
    return {
        "schema": ident.get("schema"),
        "version": ident.get("version"),
        "state_list": ident.get("state_list"),
        "parent_states": ident.get("parent_timeframe_states"),
        "valid_transitions": ident.get("valid_transitions"),
        "states": states,
        "constructors": constructors,
    }


def read_resolver_states() -> list:
    """Resolver predicates declared in market_crt_states.yaml (constructor-scope check)."""
    doc = _load_yaml(REPO_ROOT / "configs" / "formulas" / "market_crt_states.yaml")
    return [s.get("name") for s in (doc.get("states") or []) if isinstance(s, dict)]


def git_facts() -> dict:
    def _run(args):
        try:
            return subprocess.run(args, cwd=REPO_ROOT, capture_output=True, text=True,
                                  timeout=20).stdout.strip()
        except Exception:
            return ""
    return {"commit": _run(["git", "rev-parse", "HEAD"]) or "UNKNOWN",
            "branch": _run(["git", "rev-parse", "--abbrev-ref", "HEAD"]) or "UNKNOWN"}

# ----------------------------- the bridge proper -----------------------------
# One record per trading concept. Each field is either (a) read from a live authority at
# generation time, or (b) a declared constant NAMING the authority. No record restates math.

CONCEPTS: list[dict] = [
    {
        "id": "C-001",
        "concept": "OHLCV",
        "ontology_section": "source_inputs",
        "observable_definition":
            "The five raw ingested columns per bar: open, high, low, close, volume. As-ingested, "
            "no computation, no transform. The DAG roots every other identity grounds out at.",
        "feature_representation":
            "FM-085 open, FM-086 high, FM-087 low, FM-088 close, FM-089 volume",
        "state_representation": "none - no states block; raw measurement, never banded",
        "authority_module":
            "features.feature_pipeline.FeaturePipeline (ingestion); "
            "data_ingestion.ohlcv_schema.require_ohlcv_columns (contract)",
        "storage_representation":
            "vector indices 0-4; enriched_df float64/int64; feature_vectors float32",
        "evidence_artifact":
            "FeaturePipeline.run() -> feature_vectors shape (N, 48); validate_ohlcv_frame(); "
            "raw OHLCV identity/hash never mutated",
        "observability": "directly_observable",
        "status": "present",
        "fm_ids": ["FM-085", "FM-086", "FM-087", "FM-088", "FM-089"],
        "notes":
            "volume is TICK_VOLUME identity on Forex; a distinct volume_range_proxy column "
            "exists for the zero-volume case (Phase-1 identity closure).",
    },
    {
        "id": "C-002",
        "concept": "Range",
        "ontology_section": "structural_states (foundation) + crt_state_identity (state)",
        "observable_definition":
            "A frozen reference envelope: h_ref = max(high) / l_ref = min(low) over a seed window, "
            "against which a later bar can be tested for boundary pierce. The engine's founding "
            "object for the whole CRT traversal.",
        "feature_representation":
            "none directly - h_ref/l_ref are reference BOUNDARIES, not vector slots; they enter "
            "the vector only through derived distances",
        "state_representation":
            "CRTState.RANGE (M15 execution ground, CRT-S-RANGE); RANGE_C1 (CRT-S-RANGE_C1, ground "
            "of the disjoint parent_three_candle subgraph)",
        "authority_module":
            "config_layer.m15_structural_range.M15StructuralLiquidityRange (aliased Range in "
            "crt_engine_v2); crt_engine_v2.RangeDetector",
        "storage_representation":
            "engine state enumeration; logs/crt_transitions.jsonl (state_entry_counts['RANGE'])",
        "evidence_artifact":
            "crt_transitions.jsonl TRANSITION_COUNTER block; state_distribution per-bar occupancy "
            "in the run summary JSON",
        "observability": "derived",
        "status": "present",
        "fm_ids": [],
        "notes":
            "NOT the same node as RANGE_C1 - do not collapse (crt_state_identity.yaml:365). "
            "HTFBuilder is the reset clock; M15StructuralLiquidityRange is this object. RANGE has "
            "TWO increment sites, so state_entry_counts['RANGE'] counts entered-or-re-entered.",
    },
    {
        "id": "C-003",
        "concept": "Liquidity",
        "ontology_section": "derived_metrics + structural_states",
        "observable_definition":
            "Resting reference levels where price has previously reversed or paused, expressed as an "
            "ATR-normalized distance from current close to the nearest such level, plus a bounded "
            "pressure score derived from that distance.",
        "feature_representation":
            "FM-025 liquidity_distance (idx 36), FM-026 liquidity_pressure_score (idx 37), "
            "FM-058 liquidity_sweep (idx 21), FM-059 sweep_detected (idx 20), FM-060 double_sweep (idx 6)",
        "state_representation":
            "liquidity_sweep {-1 SellSideSweep, 0 NoSweep, 1 BuySideSweep}; sweep_detected "
            "{0 NoSweep, 1 SweepDetected}; double_sweep {0 NoDoubleSweep, 1 DoubleSweep}",
        "authority_module":
            "features.derived_math.liquidity_distance / liquidity_pressure_score; "
            "features.feature_pipeline.compute_canonical_structure_features",
        "storage_representation":
            "vector indices 6, 20, 21, 36, 37; taxonomy.category = Liquidity",
        "evidence_artifact":
            "feature vector values; FeatureMonitor drift report; causal_structure_series() arrays",
        "observability": "derived",
        "status": "present",
        "fm_ids": ["FM-025", "FM-026", "FM-058", "FM-059", "FM-060"],
        "notes":
            "liquidity_distance carries a 10.0 NaN sentinel feeding liquidity_pressure_score's "
            "exp decay (nan_sentinel=10.0, decay_coeff=-0.5).",
    },
    {
        "id": "C-004",
        "concept": "Sweep",
        "ontology_section": "structural_predicates (SP-001 swept_boundary)",
        "observable_definition":
            "A bar pierces a reference boundary and closes BACK on the origin side: "
            "swept_high := high > h_ref AND close < h_ref; swept_low := low < l_ref AND close > l_ref. "
            "Price took the level and failed to hold beyond it.",
        "feature_representation":
            "FM-058 liquidity_sweep (idx 21, signed), FM-059 sweep_detected (idx 20, binary), "
            "FM-060 double_sweep (idx 6)",
        "state_representation":
            "CRTState.SWEEP (CRT-S-SWEEP); feature states SellSideSweep/BuySideSweep/NoSweep",
        "authority_module":
            "structure.predicates.swept_high / swept_low (SP-001 single implementation, SK-1); "
            "crt_engine_v2.RangeDetector.detect_sweep delegates to the same kernel",
        "storage_representation":
            "vector indices 6, 20, 21; engine state; utils/sweep_trace_logger sweep trace packets",
        "evidence_artifact":
            "sweep trace packets (SweepTraceLogger); crt_transitions.jsonl; "
            "last_resolver_evidence['sweep_sig']",
        "observability": "derived",
        "status": "present",
        "fm_ids": ["FM-058", "FM-059", "FM-060"],
        "notes":
            "sweep_price is the bar's OWN piercing extreme (high on a high sweep), never the "
            "reference level. SP-001 collapsed NINE executable copies into one kernel (crt_engine_v2 "
            "x3, parent_crt, crt_state_resolver, visual_crt x2, weekly_range x2).",
    },
    {
        "id": "C-005",
        "concept": "Displacement",
        "ontology_section":
            "structural_predicates (SP-002 directional_impulse) + derived_metrics + structural_states",
        "observable_definition":
            "Travel AWAY from the swept side with a bodied move that cleared the swept level "
            "(SP-002), and/or a body-dominated candle (body_size > candle_range * strong_body_mult) "
            "whose range is large against ATR.",
        "feature_representation":
            "FM-020 disp_strength (idx 33), FM-028 displacement_atr_ratio, FM-029 "
            "disp_strength_atr_rescale, FM-069 displacement_flag (non-vector); FM-010 body_ratio "
            "(idx 29) is the CRT gate quantity (>= 0.70)",
        "state_representation":
            "CRTState.DISPLACEMENT (CRT-S-DISPLACEMENT); displacement_flag {0 NoDisplacement, "
            "1 Displacement}; body_commitment {Low/Medium/HighCommitment}",
        "authority_module":
            "crt_engine_v2.StateMachine.try_sweep_to_displacement; features.derived_math.disp_strength "
            "/ displacement_atr_ratio / disp_strength_atr_rescale; config_layer.structure_profiles",
        "storage_representation":
            "vector index 33 (FM-020); FM-069 is a declared NON-vector stateful identity; "
            "logs/crt_transitions.jsonl",
        "evidence_artifact":
            "crt_transitions.jsonl (SWEEP->DISPLACEMENT transition + reason); sweep trace packet; "
            "telemetry displacement_success counter",
        "observability": "derived",
        "status": "present",
        "fm_ids": ["FM-020", "FM-010"],
        "non_vector_fm_ids": ["FM-028", "FM-029", "FM-069"],
        "notes":
            "FOUR distinct identities share the word 'displacement' - FM-020 body/(atr*close), "
            "FM-028 candle_range/atr, FM-029 disp_strength/atr, and the CRTState. Do not alias "
            "them (GD-004 / FU-CRT-MOVE-MISWIRE).",
    },
    {
        "id": "C-006",
        "concept": "FVG (Fair Value Gap)",
        "ontology_section": "derived_metrics",
        "observable_definition":
            "A 3-candle imbalance at interior position i, tested with candles i-1 and i+1: BULLISH "
            "when bars[i-1].high < bars[i+1].low (zone [bars[i-1].high, bars[i+1].low]); BEARISH "
            "when bars[i-1].low > bars[i+1].high. Reported as distance to the most recent UNFILLED "
            "zone. FILLED once price trades back through any part of the zone.",
        "feature_representation": "FM-076 fvg_distance (idx 40), signed ATR-normalized tanh-bounded",
        "state_representation":
            "none - continuous distance; no states block. Fill status is internal to the zone object",
        "authority_module":
            "features.smc.fvg.fvg_distance (impl); features.smc.fvg.find_active_fvg (zone); "
            "features.smc._geometry.signed_atr_distance",
        "storage_representation": "vector index 40; Zone dataclass (high, low, formed_at_index, bullish)",
        "evidence_artifact":
            "fvg_distance value in the canonical vector; find_active_fvg() Zone return",
        "observability": "derived",
        "status": "present",
        "fm_ids": ["FM-076"],
        "notes":
            "IS ontology-declared (derived_metrics.fvg_distance) - NOT a temporal_derivation. "
            "temporal_derivations.fair_value_gap exists only in the DISABLED "
            "configs/market_reality/market_reality_v1.yaml contract (enabled: false), where it was "
            "recorded GENUINELY_ABSENT; FM-076 closes that gap.",
    },
    {
        "id": "C-007",
        "concept": "Order Block",
        "ontology_section": "derived_metrics",
        "observable_definition":
            "The last OPPOSITE-coloured candle immediately preceding a structural break: BULLISH OB = "
            "the last down-close candle before a close above the most recent confirmed swing high; "
            "BEARISH OB = the symmetric case. Zone = that origin candle's full [low, high]. "
            "MITIGATED once price later overlaps the zone (any touch, not a close).",
        "feature_representation":
            "FM-075 order_block_distance (idx 39), signed ATR-normalized tanh-bounded distance to the "
            "most recent UNMITIGATED OB's near edge",
        "state_representation":
            "none - continuous distance; no states block. Mitigation is internal Zone state",
        "authority_module":
            "features.smc.order_block.order_block_distance (impl); find_active_order_block; "
            "_origin_candle; _find_break_events; features.smc._geometry.detect_causal_swings",
        "storage_representation":
            "vector index 39; Zone dataclass (high, low, formed_at_index, bullish)",
        "evidence_artifact":
            "order_block_distance value in the canonical vector; find_active_order_block() Zone return",
        "observability": "derived",
        "status": "present",
        "fm_ids": ["FM-075"],
        "notes":
            "Mitigation is scanned from the CONFIRMING BREAK, not the origin - the break candle "
            "geometrically overlaps the origin range. `break_events` is memoizable across the three "
            "break-event families (OB/breaker/mitigation), pinned by test_smc_break_event_memo.py.",
    },
    {
        "id": "C-008",
        "concept": "Breaker Block",
        "ontology_section": "derived_metrics",
        "observable_definition":
            "An ORDER BLOCK that has been FULLY VIOLATED - a later candle CLOSES beyond the zone's "
            "far edge (not merely a wick touch/mitigation). The broken zone then FLIPS polarity: a "
            "failed bullish OB becomes a bearish breaker, and vice versa. Active until retested.",
        "feature_representation":
            "FM-077 breaker_distance (idx 41), signed ATR-normalized tanh-bounded distance to the "
            "most recent un-retested breaker's near edge",
        "state_representation":
            "none - continuous distance; no states block. Polarity flip is internal Zone state",
        "authority_module":
            "features.smc.breaker.breaker_distance (impl) + find_active_breaker; reuses "
            "order_block._find_break_events / _origin_candle (intra-package reuse)",
        "storage_representation": "vector index 41; Zone with bullish = not origin.bullish",
        "evidence_artifact":
            "breaker_distance value in the canonical vector; find_active_breaker() Zone return",
        "observability": "derived",
        "status": "present",
        "fm_ids": ["FM-077"],
        "notes":
            "The violation test is CLOSE-based (c.close < ob.low for a bullish OB), deliberately "
            "stricter than mitigation's touch-based test - that distinction is what separates "
            "FM-077 from FM-075.",
    },
    {
        "id": "C-009",
        "concept": "Mitigation Block",
        "ontology_section": "derived_metrics",
        "observable_definition":
            "Once an order block's OUTER zone has been touched at least once, the CANDLE BODY "
            "(open/close range, narrower than the wick range) of the SAME origin candle is the deeper "
            "level. The mitigation block is that inner body-only zone, live only after the outer "
            "zone is touched and before the inner zone is entered.",
        "feature_representation":
            "FM-078 mitigation_block_distance (idx 42), signed ATR-normalized tanh-bounded",
        "state_representation": "none - continuous distance; no states block",
        "authority_module":
            "features.smc.mitigation.mitigation_block_distance (impl) + "
            "find_active_mitigation_block; reuses order_block helpers",
        "storage_representation": "vector index 42; Zone(high=body_high, low=body_low)",
        "evidence_artifact":
            "mitigation_block_distance value; find_active_mitigation_block() Zone return",
        "observability": "derived",
        "status": "present",
        "fm_ids": ["FM-078"],
        "notes":
            "Deliberately a DIFFERENT distance from FM-075, not an alias. Degenerate doji "
            "(open == close) yields no usable inner zone and is skipped.",
    },
    {
        "id": "C-010",
        "concept": "HTF Context",
        "ontology_section": "htf_states (SEM-008 HTF_STATE)",
        "observable_definition":
            "Posture of a CLOSED parent candle against the previous closed parent: EXPANSION (close "
            "breaks previous parent), REVERSAL (close breaks previous parent opposite the previous "
            "body), DISTRIBUTION (close inside previous parent and range_ratio >= "
            "distribution_min), ACCUMULATION (close inside and not DISTRIBUTION). First closed "
            "parent is UNKNOWN.",
        "feature_representation":
            "none on the vector - HTF posture is a PARENT-scoped enum, not a per-bar vector slot. "
            "Parent OHLC comes from ParentCandleBuilder (calendar-true) or HTFBuilder (count clock)",
        "state_representation":
            "HTFState enum {EXPANSION, ACCUMULATION, DISTRIBUTION, REVERSAL, (+UNKNOWN)}; orthogonal "
            "to C1/C2/C3; explicitly NOT CRTState",
        "authority_module":
            "config_layer.htf_state.classify_htf_state(prev, curr, thresholds); "
            "features.parent_candle.ParentCandleBuilder (calendar periods H1/H4/D1/W1/MN1); "
            "runtime.backtest_v2.HTFBuilder (count-based, distinct)",
        "storage_representation":
            "parent_history deque (up to `keep` CLOSED parents, oldest first); enum value; "
            "parent_crt.htf_state config section",
        "evidence_artifact":
            "classify_htf_state() HTFState return; ParentCandleBuilder.parent_history; "
            "HTFBuilder.parent_candle",
        "observability": "derived",
        "status": "present_unwired",
        "fm_ids": [],
        "notes":
            "Unwired until CH-htf-state-objective. ParentCandleBuilder NEVER exposes the in-progress "
            "period's accumulator (no-lookahead, adversarially tested). HTFBuilder and "
            "ParentCandleBuilder answer DIFFERENT questions and must not be conflated.",
    },
    {
        "id": "C-011",
        "concept": "Manipulation",
        "ontology_section": "crt_state_identity (parent_three_candle subgraph) + objectives/phases",
        "observable_definition":
            "At parent scale: a C2 candle sweeps the C1 boundary and closes back inside - the "
            "parent-timeframe sweep. A C2 sweep alone does NOT set parent bias; bias requires "
            "DISTRIBUTION_C3 (F-074 at parent scale).",
        "feature_representation":
            "none on the vector at the parent node - the parent track is driven by parent OHLC, not "
            "per-bar vector slots. The M15-scale analogue is FM-058 liquidity_sweep / SP-001",
        "state_representation":
            "MANIPULATION_C2 (CRT-S-MANIPULATION_C2), subgraph parent_three_candle, occupancy_class "
            "event, requires_memory true, can_emit_bias FALSE, can_emit_signal FALSE",
        "authority_module":
            "configs/formulas/crt_state_identity.yaml (identity); runtime/parent_crt.py "
            "(constructor); src/research/sujan_manipulation/ (a DIFFERENT research object, SEM-031)",
        "storage_representation":
            "CRT state enumeration (parent subgraph); valid_transitions RANGE_C1 -> MANIPULATION_C2",
        "evidence_artifact":
            "parent_crt state traversal; valid_transitions edge RANGE_C1[MANIPULATION_C2, RANGE_C1]",
        "observability": "derived",
        "status": "present_no_resolver_predicate",
        "fm_ids": [],
        "notes":
            "THREE distinct objects share this word: MANIPULATION_C2 (parent CRT), "
            "sujan_manipulation_phase1 (research, purges an EXTERNALLY SUPPLIED parent bulk candle; "
            "founding at UNK-007), and M15 SP-001 sweeps. F-077: do not collapse. "
            "market_crt_states.yaml declares NO MANIPULATION_C2 predicate, so the resolver "
            "constructor cannot reach it.",
    },
    {
        "id": "C-012",
        "concept": "Distribution",
        "ontology_section": "crt_state_identity (parent) + htf_states (SEM-008)",
        "observable_definition":
            "At parent scale: a directional impulse AWAY from the swept side, confirming C2 - the ONLY "
            "parent state permitted to emit bias. Distinct from the statistical sense (a sample "
            "distribution) and from HTFState.DISTRIBUTION (close inside previous parent with "
            "range_ratio >= distribution_min).",
        "feature_representation":
            "none on the vector at the parent node; the statistical sense is measured by "
            "backtest_v2.DistributionAnalyser, not by a feature",
        "state_representation":
            "DISTRIBUTION_C3 (CRT-S-DISTRIBUTION_C3), subgraph parent_three_candle, can_emit_bias "
            "TRUE (the only such state), can_emit_signal FALSE; separately HTFState.DISTRIBUTION",
        "authority_module":
            "configs/formulas/crt_state_identity.yaml (identity); runtime/parent_crt.py "
            "(can_emit_bias at parent_crt.py:102-110); config_layer.htf_state (HTFState member); "
            "runtime/backtest_v2.DistributionAnalyser (statistical sense)",
        "storage_representation":
            "CRT state enumeration (parent subgraph); valid_transitions MANIPULATION_C2 -> "
            "DISTRIBUTION_C3",
        "evidence_artifact":
            "parent_crt state traversal + emitted parent bias; backtest_v2 regime/session "
            "distribution blocks in the run summary",
        "observability": "derived",
        "status": "present_no_resolver_predicate",
        "fm_ids": [],
        "notes":
            "F-077 TRIPLE COLLISION: DISTRIBUTION_C3 != HTFState.DISTRIBUTION != Romeo/Sujan 4H "
            "'State 3 Distribution' (near-INVERTED meaning at the parent node). Do not collapse any "
            "pair. market_crt_states.yaml declares NO DISTRIBUTION_C3 predicate.",
    },
    {
        "id": "C-013",
        "concept": "CHoCH (Change of Character)",
        "ontology_section": "structural_states",
        "observable_definition":
            "A break-of-structure event that goes AGAINST the prevailing trend. A break agreeing "
            "with the trend is ordinary continuation (BOS), not CHoCH. Pure algebra over two "
            "already-registered identities - no new detection state machine, no pivot scan.",
        "feature_representation":
            "FM-083 change_of_character (idx 47), signed {-1, 0, +1}; derived from FM-057 "
            "break_of_structure (idx 22) x FM-054 trend_bias (idx 10)",
        "state_representation":
            "change_of_character {-1 BearishCHoCH, 0 NoCHoCH, 1 BullishCHoCH}",
        "authority_module":
            "features.smc.choch.change_of_character(break_of_structure, trend_bias)",
        "storage_representation": "vector index 47; taxonomy.category = MarketStructure",
        "evidence_artifact": "change_of_character value; FeatureStateEncoder state BearishCHoCH/NoCHoCH/BullishCHoCH",
        "observability": "derived",
        "status": "present",
        "fm_ids": ["FM-083", "FM-057", "FM-054"],
        "notes":
            "Returns 0.0 when there is no break, no defined trend to change FROM (trend_bias == 0), "
            "or the break agrees with the trend. The ontology excludes BOS/CHOCH/PIVOT detection "
            "state-machines (market_ontology.yaml:32) - this module adds NONE; it recombines output "
            "the registry already governs.",
    },
    {
        "id": "C-014",
        "concept": "EQH (Equal Highs)",
        "ontology_section": "derived_metrics",
        "observable_definition":
            "Two or more confirmed swing highs within a small ATR-scaled tolerance of each other - "
            "the standard resting-liquidity-pool reading (the market treats near-equal highs as one "
            "larger liquidity target, not independent levels).",
        "feature_representation":
            "FM-081 eqh_distance (idx 45), signed ATR-normalized tanh-bounded distance to the nearest "
            "equal-highs cluster above",
        "state_representation": "none - continuous distance; no states block",
        "authority_module":
            "features.smc.levels.eqh_eql_distance (impl) + _nearest_equal_cluster; "
            "features.smc._geometry.collect_causal_swings",
        "storage_representation":
            "vector index 45; tolerance default tolerance_atr=0.1, max_swings=8; 0.0 when no cluster",
        "evidence_artifact": "eqh_distance value in the canonical vector; eqh_eql_distance() tuple",
        "observability": "derived",
        "status": "present",
        "fm_ids": ["FM-081"],
        "notes":
            "Extends FM-025/FM-026 (single-swing liquidity approximation) to CLUSTERS of swings. "
            "Returns 0.0 when atr <= 0 or fewer than 2 swings are confirmed.",
    },
    {
        "id": "C-015",
        "concept": "EQL (Equal Lows)",
        "ontology_section": "derived_metrics",
        "observable_definition":
            "Two or more confirmed swing lows within a small ATR-scaled tolerance of each other. The "
            "symmetric counterpart of EQH; same resting-liquidity-pool reading.",
        "feature_representation":
            "FM-082 eql_distance (idx 46), signed ATR-normalized tanh-bounded distance to the nearest "
            "equal-lows cluster below",
        "state_representation": "none - continuous distance; no states block",
        "authority_module":
            "features.smc.levels.eqh_eql_distance (impl, shared with EQH); "
            "features.smc._geometry.collect_causal_swings(kind='low')",
        "storage_representation": "vector index 46; same tolerance/limits as EQH; 0.0 when no cluster",
        "evidence_artifact": "eql_distance value in the canonical vector; eqh_eql_distance() tuple",
        "observability": "derived",
        "status": "present",
        "fm_ids": ["FM-082"],
        "notes":
            "EQH and EQL share ONE implementation (eqh_eql_distance returns a 2-tuple) and are "
            "declared as two separate ontology identities with two separate vector slots.",
    },
    {
        "id": "C-016",
        "concept": "PDH (Previous-Day High)",
        "ontology_section": "derived_metrics",
        "observable_definition":
            "The high of the most recently CLOSED D1 parent candle (a calendar-true daily close, not "
            "a count-based window). Reported as a signed distance from current close to that level.",
        "feature_representation":
            "FM-079 pdh_distance (idx 43), signed ATR-normalized tanh-bounded; "
            "favorable_sign=-1 (below PDH = inside)",
        "state_representation": "none - continuous distance; no states block",
        "authority_module":
            "features.smc.levels.pdh_pdl_distance (impl, shared with PDL); "
            "features.parent_candle.ParentCandleBuilder('D1', keep>=1).parent_history",
        "storage_representation":
            "vector index 43; source is the shared D1 builder's parent_history (one D1 builder per "
            "M15 pipeline, not one per consumer)",
        "evidence_artifact":
            "pdh_distance value; ParentCandleBuilder.parent_history[-1].high",
        "observability": "derived",
        "status": "present",
        "fm_ids": ["FM-079"],
        "notes":
            "NEVER derived from HTFBuilder - that is a count-based reset clock whose boundaries are "
            "stream-offset dependent, not calendar-aligned. (0.0, 0.0) when no D1 parent has closed.",
    },
    {
        "id": "C-017",
        "concept": "PDL (Previous-Day Low)",
        "ontology_section": "derived_metrics",
        "observable_definition":
            "The low of the most recently CLOSED D1 parent candle. Reported as a signed distance "
            "from current close to that level.",
        "feature_representation":
            "FM-080 pdl_distance (idx 44), signed ATR-normalized tanh-bounded; "
            "favorable_sign=+1 (above PDL = inside)",
        "state_representation": "none - continuous distance; no states block",
        "authority_module":
            "features.smc.levels.pdh_pdl_distance (impl, shared with PDH); "
            "features.parent_candle.ParentCandleBuilder('D1', keep>=1)",
        "storage_representation": "vector index 44; same shared D1 builder as PDH",
        "evidence_artifact": "pdl_distance value; ParentCandleBuilder.parent_history[-1].low",
        "observability": "derived",
        "status": "present",
        "fm_ids": ["FM-080"],
        "notes":
            "PDH/PDL are the location gate named explicitly in the parent-candle/SMC program study. "
            "PDH and PDL share ONE implementation and are declared as two identities.",
    },
]


# --------------------------------- validation --------------------------------

REQUIRED_CONCEPT_FIELDS = (
    "id", "concept", "observable_definition", "feature_representation",
    "state_representation", "authority_module", "storage_representation",
    "evidence_artifact", "observability", "status",
)
VALID_STATUS = {
    "present", "present_unwired", "present_no_resolver_predicate",
    "present_constructor_unreachable", "present_undefined", "absent",
}
VALID_OBSERVABILITY = {"directly_observable", "derived"}


def validate(schema: dict, ont: dict, concepts: list, resolver_states: list) -> list:
    """Return a list of problem strings. Empty list == bridge is internally consistent.

    Distinguishes VECTOR-BOUND FM ids (`fm_ids`, must be in `_FM_ID_TO_NAME`) from DECLARED
    NON-VECTOR FM ids (`non_vector_fm_ids`, must exist in the ontology but must NOT be
    vector-bound). Conflating the two was the first real defect this gate caught.
    """
    problems: list[str] = []

    feats = schema["features"]
    if len(feats) != schema["dim"]:
        problems.append(f"CANONICAL_FEATURES has {len(feats)} entries, dim says {schema['dim']}")
    if len(set(feats)) != len(feats):
        problems.append(f"duplicate canonical feature names: {sorted(set(feats))}")

    fm_vals = list(schema["fm_to_name"].values())
    if set(fm_vals) != set(feats):
        problems.append(
            "FM-ID map is not bijective with CANONICAL_FEATURES: "
            f"{sorted(set(feats) ^ set(fm_vals))}"
        )
    if len(fm_vals) != len(set(fm_vals)):
        problems.append("two FM ids bound to the same canonical feature name")

    seen_ids: set = set()
    for c in concepts:
        cid = c.get("id", "<no id>")
        if cid in seen_ids:
            problems.append(f"{cid}: duplicate concept id")
        seen_ids.add(cid)
        for f in REQUIRED_CONCEPT_FIELDS:
            if not c.get(f):
                problems.append(f"{cid} ({c.get('concept')}): missing/empty field {f!r}")
        if c.get("status") not in VALID_STATUS:
            problems.append(f"{cid}: unknown status {c.get('status')!r}")
        if c.get("observability") not in VALID_OBSERVABILITY:
            problems.append(f"{cid}: unknown observability {c.get('observability')!r}")
        if c.get("status") == "absent" and c.get("authority_module"):
            problems.append(f"{cid}: status absent but authority_module is set")
        if str(c.get("status", "")).startswith("present") and not c.get("authority_module"):
            problems.append(f"{cid}: status present but authority_module is empty")

    known_fm = set(schema["fm_to_name"])
    for c in concepts:
        for fm in c.get("fm_ids", []):
            if fm not in known_fm:
                problems.append(
                    f"{c.get('id')}: cites vector-bound FM id {fm!r} which is NOT in "
                    f"_FM_ID_TO_NAME (declared non-vector identities belong in "
                    f"non_vector_fm_ids)"
                )

    # declared-but-non-vector identities: must exist in the ontology, must NOT be vector-bound
    ont_fm_all = {e["fm_id"] for e in ont["entries"].values() if e.get("fm_id")}
    for c in concepts:
        for fm in c.get("non_vector_fm_ids", []):
            if fm in known_fm:
                problems.append(
                    f"{c.get('id')}: lists {fm!r} as non-vector but it IS vector-bound"
                )
            elif fm not in ont_fm_all:
                problems.append(
                    f"{c.get('id')}: non_vector_fm_ids cites {fm!r} which no ontology "
                    f"entry declares"
                )

    for c in concepts:
        if c.get("status") == "present_no_resolver_predicate" and c.get("concept") in resolver_states:
            problems.append(
                f"{c.get('id')}: declared present_no_resolver_predicate but "
                f"{c.get('concept')!r} IS a resolver state"
            )
    return problems


def coverage_report(schema: dict) -> dict:
    """Which canonical features the bridge names, and which it does not."""
    named = set()
    for c in CONCEPTS:
        for fm in c.get("fm_ids", []):
            nm = schema["fm_to_name"].get(fm)
            if nm:
                named.add(nm)
    return {
        "canonical_total": len(schema["features"]),
        "named_count": len(named),
        "named_by_a_concept": sorted(named),
        "not_named": sorted(set(schema["features"]) - named),
    }


# --------------------------------- measurement --------------------------------

def measure_dtypes() -> dict:
    """Measure the REAL dtypes by running FeaturePipeline.run() on a data slice.

    Returns {} when the corpus is unavailable (the HTML then says 'not measured' rather than
    inventing a dtype). This is a measurement, not a declaration.
    """
    src = REPO_ROOT / "data" / "mt5" / "XAUUSD_M15.csv"
    if not src.exists():
        return {}
    try:
        import logging
        import warnings
        import pandas as pd
        logging.disable(logging.CRITICAL)
        warnings.filterwarnings("ignore")
        from features.feature_pipeline import FeaturePipeline
        from data_ingestion.corpus_store import load as _corpus_load  # CH-corpus-ssot: the corpus SSOT
        df = _corpus_load(src).frame(nrows=400)
        pipe = FeaturePipeline(df)
        enriched, vectors = pipe.run()
        logging.disable(logging.NOTSET)
        return {
            "source": "data/mt5/XAUUSD_M15.csv (first 400 rows)",
            "enriched": {k: str(t) for k, t in enriched.dtypes.items()},
            "vector_dtype": str(vectors.dtype),
            "shape": [int(vectors.shape[0]), int(vectors.shape[1])],
        }
    except Exception as exc:  # noqa: BLE001 — a measurement failure must not break generation
        return {"error": f"{type(exc).__name__}: {exc}"}


def render_html(schema: dict, ont: dict, dt: dict) -> str:
    entries = ont["entries"]
    enriched = (dt or {}).get("enriched") or {}
    vdt = (dt or {}).get("vector_dtype") or "not measured"
    shape = (dt or {}).get("shape")
    rows = []
    for i, name in enumerate(schema["features"]):
        meta = entries.get(name, {})
        fm = schema["name_to_fm"].get(name, "")
        kind = meta.get("knowledge_class") or ""
        rows.append(
            "<tr>"
            f'<td class="n">{i}</td>'
            f"<td><code>{name}</code></td>"
            f"<td><code>{enriched.get(name, '&mdash;')}</code></td>"
            f"<td><code>{vdt if vdt != 'not measured' else '&mdash;'}</code></td>"
            f"<td><code>{fm}</code></td>"
            f"<td>{meta.get('section', '&mdash;')}</td>"
            f"<td>{meta.get('category', '&mdash;')}</td>"
            f"<td>{kind}</td>"
            f"<td><code>{meta.get('impl') or '&mdash;'}</code></td>"
            "</tr>"
        )
    tbl = "\n".join(rows)
    meas = (f"Measured by <code>FeaturePipeline.run()</code> on {dt.get('source')} "
            f"&rarr; <code>feature_vectors</code> shape <code>{shape}</code>. "
            "Warmup NaN rows are dropped by <code>finalize()</code>, so row count &lt; input rows."
            if shape else
            "Dtypes were NOT measured at generation time (corpus unavailable). "
            "Re-run <code>python scripts/analysis/gen_bridge_layer.py</code> with "
            "<code>data/mt5/XAUUSD_M15.csv</code> present.")
    return HTML_TEMPLATE.format(
        dim=schema["dim"],
        schema_hash=schema["schema_hash"],
        order_hash=schema["order_hash"],
        nrows=len(rows),
        measurement=meas,
        rows=tbl,
    )


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CANONICAL_FEATURES &mdash; Bridge Layer</title>
<style>
  :root {{ --bg:#f4f1ea; --ink:#1c1915; --muted:#5c564c; --line:#ddd6c8; --head:#efeae0; }}
  * {{ box-sizing: border-box; }}
  body {{ margin:0; background:var(--bg); color:var(--ink);
         font:15px/1.45 "Segoe UI", Candara, sans-serif; }}
  main {{ max-width:72rem; margin:0 auto; padding:1.25rem; }}
  h1 {{ font-size:1.35rem; margin:0 0 .4rem; }}
  p {{ margin:.35rem 0 .8rem; }}
  code {{ font-family: Consolas, "Cascadia Mono", monospace; font-size:.88em; }}
  table {{ border-collapse:collapse; width:100%; background:#fff; font-size:.86rem; }}
  th, td {{ border-bottom:1px solid var(--line); text-align:left; padding:.3rem .45rem;
           vertical-align:top; }}
  th {{ background:var(--head); color:var(--muted); font-weight:600; position:sticky; top:0; }}
  td.n {{ font-variant-numeric: tabular-nums; width:2.4rem; }}
  .note {{ color:var(--muted); font-size:.85rem; }}
</style>
</head>
<body>
<main>

<h1>CANONICAL_FEATURES</h1>
<p>
  Schema dimension <code>{dim}</code>. <code>SCHEMA_HASH</code>
  <code>{schema_hash}</code>. <code>FEATURE_ORDER_HASH</code>
  <code>{order_hash}</code>. <strong>{nrows} names</strong> &mdash; this is the exact column
  order of <code>FeaturePipeline.feature_vectors</code>.
</p>
<p class="note">{measurement}</p>
<p class="note">
  Vector index is NOT the frame's column position. <code>section</code> is the
  <code>market_ontology.yaml</code> section that declares the identity;
  <code>impl</code> is the named callable the ontology binds it to (never <code>eval</code>'d).
  Generated by <code>scripts/analysis/gen_bridge_layer.py</code> &mdash; do not edit by hand.
</p>
<table>
<thead>
<tr>
  <th>#</th><th>Name</th><th>enriched_df dtype</th><th>feature_vectors dtype</th>
  <th>FM-ID</th><th>Ontology section</th><th>Category</th>
  <th>Knowledge class</th><th>Bound implementation</th>
</tr>
</thead>
<tbody>
{rows}
</tbody>
</table>

</main>
</body>
</html>
"""


# --------------------------------- renderers ----------------------------------

def render_concepts_yaml(schema: dict, cov: dict, git: dict) -> str:
    """Machine-readable concept records — the bridge's primary artifact."""
    import yaml
    doc = {
        "schema_version": "bridge_layer/1.0",
        "generated_by": "scripts/analysis/gen_bridge_layer.py",
        "generated_from": {
            "commit": git["commit"],
            "branch": git["branch"],
            "feature_schema_dim": schema["dim"],
            "schema_hash": schema["schema_hash"],
            "feature_order_hash": schema["order_hash"],
        },
        "ontologies": [
            {"layer": "Measurement", "authority": "src/features/feature_schema.py"},
            {"layer": "Feature", "authority": "configs/formulas/market_ontology.yaml"},
            {"layer": "State", "authority": "src/features/feature_states.py"},
            {"layer": "Decision", "authority": "configs/formulas/crt_state_identity.yaml"},
            {"layer": "MarketReality", "authority":
                "configs/market_reality/market_reality_v1.yaml (enabled: false)"},
        ],
        "status_vocabulary": {
            "present": "declared + authority + reachable",
            "present_unwired": "declared + authority implemented, not wired to runtime",
            "present_no_resolver_predicate":
                "declared + engine constructor; the resolver config carries no predicate",
            "present_constructor_unreachable": "declared; named blocking gap in capability contract",
            "present_undefined": "identity slot exists; no definition",
            "absent": "no declaration, no authority",
        },
        "coverage": cov,
        "concepts": CONCEPTS,
    }
    return yaml.safe_dump(doc, sort_keys=False, width=100, allow_unicode=True)


def render_feature_schema_bridge(schema: dict, ont: dict, cov: dict) -> str:
    """FM-ID <-> concept <-> vector index <-> authority mapping."""
    entries = ont["entries"]
    by_fm = {}
    for c in CONCEPTS:
        for fm in c.get("fm_ids", []):
            by_fm.setdefault(fm, []).append(c["concept"])
    lines = [
        "# feature_schema.bridge.md",
        "",
        "> **GENERATED — do not edit by hand.** Regenerate with "
        "`python scripts/analysis/gen_bridge_layer.py`.",
        "",
        "The FM-ID ↔ concept ↔ vector-index ↔ authority bridge. Every row is read from "
        "`src/features/feature_schema.py` and `configs/formulas/market_ontology.yaml` at "
        "generation time.",
        "",
        f"Schema dimension **{schema['dim']}** · `SCHEMA_HASH` `{schema['schema_hash']}` · "
        f"`FEATURE_ORDER_HASH` `{schema['order_hash']}`",
        "",
        "## Vector index ↔ identity ↔ concept",
        "",
        "| Idx | Canonical name | FM-ID | Ontology section | Category | Concept(s) |",
        "|---:|---|---|---|---|---|",
    ]
    for i, name in enumerate(schema["features"]):
        meta = entries.get(name, {})
        fm = schema["name_to_fm"].get(name, "")
        concepts = ", ".join(by_fm.get(fm, [])) or "—"
        lines.append(
            f"| {i} | `{name}` | `{fm}` | {meta.get('section', '—')} | "
            f"{meta.get('category', '—')} | {concepts} |"
        )
    # Declared-but-NON-vector identities that a concept still needs to name. These occupy no
    # canonical slot, so they cannot appear in the vector table above; omitting them would hide
    # real measured quantities from the bridge.
    fm_by_name = {e["fm_id"]: n for n, e in entries.items() if e.get("fm_id")}
    nv_rows = []
    for c in CONCEPTS:
        for fm in c.get("non_vector_fm_ids", []):
            nv_rows.append(
                f"| `{fm}` | `{fm_by_name.get(fm, '—')}` | "
                f"{entries.get(fm_by_name.get(fm), {}).get('section', '—')} | "
                f"{entries.get(fm_by_name.get(fm), {}).get('category', '—')} | {c['concept']} |"
            )
    if nv_rows:
        lines += [
            "",
            "## Declared but NOT vector-bound (no canonical slot)",
            "",
            "These identities are real, measured, and governed — but `lineage.vector_key` is "
            "empty, so they are NOT part of the 48-dim vector. A bridge that listed only vector "
            "rows would silently drop them.",
            "",
            "| FM-ID | Ontology name | Section | Category | Concept |",
            "|---|---|---|---|---|",
        ]
        lines += nv_rows
    lines += [
        "",
        "## Coverage",
        "",
        f"- Canonical features: **{cov['canonical_total']}**",
        f"- Named by at least one concept: **{cov['named_count']}**",
        f"- Not named by any concept: {len(cov['not_named'])}",
        "",
    ]
    if cov["not_named"]:
        lines.append("Features with no concept mapping (measured, not yet bridged to vocabulary):")
        lines.append("")
        for n in cov["not_named"]:
            fm = schema["name_to_fm"].get(n, "")
            lines.append(f"- `{n}` ({fm}) — {entries.get(n, {}).get('section', '—')}")
        lines.append("")
    return "\n".join(lines) + "\n"


def render_state_ontology(states: dict) -> str:
    """Layer 2: feature value -> declared semantic state."""
    specs = states["specs"]
    vb = states["vector_bound"]
    nv = [n for n in states["all_stateful"] if n not in set(vb)]
    lines = [
        "# state_ontology.md",
        "",
        "> **GENERATED — do not edit by hand.** Regenerate with "
        "`python scripts/analysis/gen_bridge_layer.py`.",
        "",
        "\"Features measure. States interpret.\" The single source of state truth is "
        "`configs/formulas/market_ontology.yaml`; the interpreter is "
        "`src/features/feature_states.py::FeatureStateEncoder`. That file owns **no numeric "
        "cuts** — it maps values it is GIVEN and raises on a missing input (no defaults).",
        "",
        "An out-of-domain value is never coerced and never dropped: it becomes an explicit, "
        "greppable marker — `X_UNMAPPED(<value>)` for a finite value outside the declared "
        "domain, `X_NON_FINITE(<value>)` for NaN/inf.",
        "",
        "## Vector-bound stateful identities",
        "",
        "| Vector idx | Feature | FM-ID | Category | Declared states |",
        "|---:|---|---|---|---|",
    ]
    for name in sorted(vb, key=lambda n: specs[n]["vector_index"] or 0):
        s = specs[name]
        sm = "; ".join(f"`{v}`={k}" for k, v in
                       sorted(s["state_map"].items(), key=lambda kv: float(kv[0])))
        lines.append(
            f"| {s['vector_index']} | `{name}` | `{s['fm_id']}` | {s['category']} | {sm} |"
        )
    lines += [
        "",
        "## Declared but NOT vector-bound",
        "",
        "These identities carry declared states but occupy **no canonical vector slot** "
        "(`lineage.vector_key: []`). A caller must supply them explicitly; the encoder will never "
        "invent them from their inputs, because that would be re-derivation.",
        "",
        "| Feature | FM-ID | Category | Declared states |",
        "|---|---|---|---|",
    ]
    for name in sorted(nv):
        s = specs[name]
        sm = "; ".join(f"`{v}`={k}" for k, v in
                       sorted(s["state_map"].items(), key=lambda kv: float(kv[0])))
        lines.append(f"| `{name}` | `{s['fm_id']}` | {s['category']} | {sm} |")
    lines += [
        "",
        "## Continuous — measured, not interpreted",
        "",
        f"**{len(states['continuous'])}** canonical features carry no `states:` block. They are "
        "values, not labels. Banding any of them requires a declared state map in the ontology "
        "FIRST; the encoder refuses to cut a band on its own.",
        "",
        ", ".join(f"`{n}`" for n in states["continuous"]),
        "",
        "## Orthogonality note",
        "",
        "State ontology (this file) is **not** the Decision ontology. A feature state is a "
        "description of one measurement; a CRT state is a position in a governed transition "
        "graph. `examples`: `trend_bias = Bullish` is a feature state; `CRTState.RETEST` is a "
        "decision state. See `crt_state_resolver_bridge.md` for the constructor that maps "
        "between them.",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_crt_concept_map(crt: dict, resolver_states: list) -> str:
    """Decision ontology: which CRT state a concept resolves to, and by which traversal."""
    st = crt["states"]
    ex = [n for n in st if st[n]["timeframe_role"] != "parent_timeframe"]
    par = [n for n in st if st[n]["timeframe_role"] == "parent_timeframe"]
    lines = [
        "# crt_engine_v2_concept_map.md",
        "",
        "> **GENERATED — do not edit by hand.** Regenerate with "
        "`python scripts/analysis/gen_bridge_layer.py`.",
        "",
        "**This file does NOT touch the engine.** `src/config_layer/crt_engine_v2.py` remains the "
        "execution authority for live trading. This is a read-only bridge describing how trading "
        "vocabulary lands on the engine's declared states and predicate kernels.",
        "",
        "## The traversal (SP-010 structural_walk)",
        "",
        "```",
        "RANGE -> SWEEP -> DISPLACEMENT -> EXPANSION -> RETEST -> EXECUTION -> RESOLUTION",
        "  ^                    + SHADOW_PENDING branch (cross-window displacement memory)",
        "  |                    + EXPIRED TTL branch",
        "  +---------------------- reset (HTF window change / session gap)",
        "```",
        "",
        "Ordered application of `SP-001 swept_boundary` -> `SP-002 directional_impulse` -> "
        "(ATR extension) -> `SP-003 retest_band` -> soft-confirmation, driven by "
        "`StateMachine.process_candle`, one transition per bar.",
        "",
        "## M15 execution states (subgraph: execution)",
        "",
        "| State | ID | Ground | Memory | Emits bias | Emits signal | Resolver predicate |",
        "|---|---|:--:|:--:|:--:|:--:|---|",
    ]
    for name in ex:
        s = st[name]
        lines.append(
            f"| `{name}` | `{s['id']}` | {'yes' if s['is_ground'] else '—'} "
            f"| {'yes' if s['requires_memory'] else '—'} "
            f"| {'**yes**' if s['can_emit_bias'] else '—'} "
            f"| {'yes' if s['can_emit_signal'] else '—'} "
            f"| {'yes' if name in resolver_states else '**no**'} |"
        )
    lines += [
        "",
        "## Parent-timeframe states (subgraph: parent_three_candle, disjoint)",
        "",
        "| State | ID | Ground | Memory | Emits bias | Emits signal | Resolver predicate |",
        "|---|---|:--:|:--:|:--:|:--:|---|",
    ]
    for name in par:
        s = st[name]
        lines.append(
            f"| `{name}` | `{s['id']}` | {'yes' if s['is_ground'] else '—'} "
            f"| {'yes' if s['requires_memory'] else '—'} "
            f"| {'**yes**' if s['can_emit_bias'] else '—'} "
            f"| {'yes' if s['can_emit_signal'] else '—'} "
            f"| {'yes' if name in resolver_states else '**no**'} |"
        )
    lines += [
        "",
        "`DISTRIBUTION_C3` is the **only** state in the whole identity with "
        "`can_emit_bias: true`.",
        "",
        "## Concept -> state landing table",
        "",
        "| Concept | Land on | Predicate kernel | Traversal step |",
        "|---|---|---|---|",
        "| Sweep | `CRTState.SWEEP` | `SP-001 swept_boundary` | RANGE -> SWEEP |",
        "| Displacement | `CRTState.DISPLACEMENT` | `SP-002 directional_impulse` | SWEEP -> DISPLACEMENT |",
        "| Retest | `CRTState.RETEST` | `SP-003 retest_band` | EXPANSION -> RETEST |",
        "| Range | `CRTState.RANGE` | — (ground) | reset / initialise_range |",
        "| Manipulation | `MANIPULATION_C2` | parent OHLC sweep of C1 boundary | parent subgraph |",
        "| Distribution | `DISTRIBUTION_C3` | parent impulse away from swept side | parent subgraph |",
        "| HTF Context | `HTFState` (NOT CRTState) | `classify_htf_state` | orthogonal |",
        "| FVG / OB / Breaker / Mitigation / PDH / PDL / EQH / EQL / CHoCH | *no CRTState* | "
        "`features/smc/*` | distance features, not states |",
        "",
        "## Declared valid transitions",
        "",
        "```yaml",
    ]
    vt = crt.get("valid_transitions") or {}
    for k, v in vt.items():
        lines.append(f"{k}: {list(v) if isinstance(v, (list, tuple)) else v}")
    lines += [
        "```",
        "",
        "## State metadata notes (verbatim from the identity authority)",
        "",
    ]
    for name in list(ex) + list(par):
        s = st[name]
        note = s.get("notes") or s.get("description") or ""
        if note:
            lines.append(f"- **`{name}`** — {note}")
    lines.append("")
    return "\n".join(lines) + "\n"


def render_resolver_bridge(crt: dict, resolver_states: list) -> str:
    """Constructor matrix: which states each constructor can actually reach, and why not."""
    st = crt["states"]
    cons = crt["constructors"]
    lines = [
        "# crt_state_resolver_bridge.md",
        "",
        "> **GENERATED — do not edit by hand.** Regenerate with "
        "`python scripts/analysis/gen_bridge_layer.py`.",
        "",
        "CRT state identity is constructor-NEUTRAL: `crt_state_identity.yaml` declares what a "
        "state IS; the engine (`crt_engine_v2.py`) and the resolver (`crt_state_resolver.py`) are "
        "two CONSTRUCTORS of that one identity. A future constructor registers under "
        "`constructors:`, never re-declares `states:`. This file is the reachability bridge "
        "between vocabulary and each constructor.",
        "",
        f"Identity schema `{crt.get('schema')}` v`{crt.get('version')}`. "
        f"{len(st)} states, {len(cons)} declared constructors.",
        "",
        "## Constructor capability contract",
        "",
        "| Constructor | runtime_eligible | reaches_signal_state | produces_trade_geometry "
        "| produces_occupancy | produces_memory | covers_states |",
        "|---|:--:|:--:|:--:|:--:|:--:|---|",
    ]
    for cname, c in cons.items():
        cap = c["capabilities"]
        lines.append(
            f"| `{cname}` | {cap.get('runtime_eligible')} "
            f"| {cap.get('reaches_signal_state')} | {cap.get('produces_trade_geometry')} "
            f"| {cap.get('produces_occupancy')} | {cap.get('produces_memory')} "
            f"| {len(cap.get('covers_states') or [])} of {len(st)} |"
        )
    lines += ["", "### Blocking gaps", ""]
    any_gap = False
    for cname, c in cons.items():
        for g in (c["capabilities"].get("blocking_gaps") or []):
            any_gap = True
            lines.append(
                f"- **`{cname}` ({g.get('id') or 'UNNAMED'})** — capability "
                f"`{g.get('capability')}`: {g.get('summary')}"
            )
    if not any_gap:
        lines.append("- none declared")
    lines += [
        "",
        "## Per-state coverage by constructor",
        "",
        "`not covered` means the constructor's capability contract does not list the state in "
        "`covers_states` — it makes no claim about it at all.",
        "",
    ]
    hdr = "| State | ID | " + " | ".join(f"`{c}`" for c in cons) + " |"
    lines += [hdr, "|---|---|" + "|".join(["---"] * len(cons)) + "|"]
    for name, s in st.items():
        cells = []
        for c in cons:
            covered = name in (cons[c]["capabilities"].get("covers_states") or [])
            cs = cons[c]["state_status"].get(name) or {}
            if not covered:
                cells.append("not covered")
            elif cs.get("defined") is False:
                cells.append("**undefined**")
            elif cs.get("reachable") is False:
                cells.append("**unreachable**")
            elif cs.get("reachable") is True:
                cells.append("reachable")
            else:
                cells.append("covered")
        lines.append(f"| `{name}` | `{s['id']}` | " + " | ".join(cells) + " |")
    lines += [
        "",
        "## Named gaps (the honest part of the bridge)",
        "",
    ]
    for name, s in st.items():
        for c in cons:
            cs = cons[c]["state_status"].get(name)
            if cs and cs.get("unreachable_reason"):
                lines.append(f"- **`{name}` / `{c}`** — {cs['unreachable_reason']}")
            if cs and cs.get("construction_diverges_from_engine"):
                lines.append(
                    f"- **`{name}` / `{c}`** — `construction_diverges_from_engine: true` "
                    "(declared divergence, not disputed)"
                )
    missing = [n for n in st if n not in resolver_states]
    if missing:
        lines += [
            "",
            "## States with no resolver predicate",
            "",
            "Declared in the identity authority, but `configs/formulas/market_crt_states.yaml` "
            "carries **no `when:` block** for them, so the resolver constructor cannot resolve "
            "them. The engine constructor is unaffected.",
            "",
        ]
        for n in missing:
            lines.append(f"- `{n}` ({st[n]['id']}) — subgraph `{st[n]['subgraph']}`")
        lines.append("")
    lines += [
        "",
        "## Reading rule",
        "",
        "`reachable` here means *this constructor's config declares and can reach the state*, "
        "NOT that a live trade path exists. Runtime eligibility is the separate "
        "`capabilities.runtime_eligible` flag, and promotion is a governance act (M4 "
        "QualificationGate -> PromotionManager) — never implied by a reachability cell.",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_readme(schema: dict, crt: dict, states: dict, cov: dict, git: dict, dt: dict) -> str:
    """The bridge's index + provenance + validation contract."""
    return f"""# bridge_layer — trading vocabulary → repository measurement authorities

> **GENERATED — do not edit by hand.** Regenerate with
> `python scripts/analysis/gen_bridge_layer.py`.

This directory is a **BRIDGE**, not a trading course. It maps trading VOCABULARY onto the
authorities the repository already owns, so that a question phrased in market terms can be
answered by naming a module, a vector slot, a state, and an artifact — not an opinion.

    OHLCV  →  Feature Ontology  →  State Ontology  →  Decision Ontology  →  Measurement Ontology

It teaches no entries and makes no directional claim. It is a **measurement system index**.

## Provenance

| Fact | Value |
|---|---|
| Generated from commit | `{git['commit']}` |
| Branch | `{git['branch']}` |
| Feature schema dimension | `{schema['dim']}` |
| `SCHEMA_HASH` | `{schema['schema_hash']}` |
| `FEATURE_ORDER_HASH` | `{schema['order_hash']}` |
| CRT identity states | `{len(crt['states'])}` |
| CRT constructors | `{len(crt['constructors'])}` |
| Vector-bound stateful identities | `{len(states['vector_bound'])}` |
| Declared non-vector stateful identities | `{len(states['all_stateful']) - len(states['vector_bound'])}` |
| Continous (uninterpreted) features | `{len(states['continuous'])}` |
| Concepts recorded | `{len(CONCEPTS)}` |
| Dtype measurement | `{dt.get('source') or dt.get('error') or 'not measured'}` |

## Source authorities (read, never modified by the generator)

| Layer | Authority | File |
|---|---|---|
| Measurement | `CANONICAL_FEATURES`, `_FM_ID_TO_NAME` | `src/features/feature_schema.py` |
| Measurement | pipeline stages | `src/features/feature_pipeline.py` |
| Feature (WHAT) | ontology sections + `impl` bindings | `configs/formulas/market_ontology.yaml` |
| State | value → declared state | `src/features/feature_states.py` |
| Decision | state identity (Tier 1) | `configs/formulas/crt_state_identity.yaml` |
| Decision | resolver predicates | `configs/formulas/market_crt_states.yaml` |
| Execution | engine traversal | `src/config_layer/crt_engine_v2.py` |
| SMC primitives | `impl` for FM-075…FM-083 | `src/features/smc/*.py` |
| Ingestion | raw OHLCV contract | `src/data_ingestion/ohlcv_schema.py` |

## Files

| File | Answers |
|---|---|
| [`CANONICAL_FEATURES.html`](CANONICAL_FEATURES.html) | What are the {schema['dim']} vector slots, their FM-IDs, sections, categories, and measured dtypes? |
| [`concepts.yaml`](concepts.yaml) | For each trading concept: observable definition, feature, state, authority, storage, evidence, observable-vs-derived, status. |
| [`feature_schema.bridge.md`](feature_schema.bridge.md) | Which concept does each vector index / FM-ID belong to? Coverage gaps. |
| [`state_ontology.md`](state_ontology.md) | Every declared feature state, vector-bound and not. |
| [`crt_engine_v2_concept_map.md`](crt_engine_v2_concept_map.md) | Which CRT state does a concept land on, via which predicate kernel? |
| [`crt_state_resolver_bridge.md`](crt_state_resolver_bridge.md) | Which states can each constructor actually reach, and what blocks the rest? |

## Generation order

1. `read_schema()` — live `CANONICAL_FEATURES`, `_FM_ID_TO_NAME`, hashes
2. `read_ontology()` — section / category / `impl` / states per feature
3. `read_states()` — `FeatureStateEncoder` inventory
4. `read_crt_identity()` + `read_resolver_states()` — 12 identities, 2 constructors, resolver scope
5. `measure_dtypes()` — real dtypes via `FeaturePipeline.run()` (degrades to "not measured")
6. `validate()` — fail-closed consistency gate
7. render → write

## Validation

```bash
# regenerate / revalidate (no writes)
python scripts/analysis/gen_bridge_layer.py --check

# regenerate artifacts
python scripts/analysis/gen_bridge_layer.py
```

The generator **fails closed**: a non-empty validation problem list aborts before any file is
written. Checks enforced:

- canonical feature count equals `CANONICAL_FEATURE_DIM`, names unique
- the FM-ID map is **bijective** onto `CANONICAL_FEATURES`
- every concept record carries all required fields and a status from the closed vocabulary
- every FM-ID cited by a concept exists in the live identity map
- a `present*` record must name an authority; an `absent` record must not
- any concept declared `present_no_resolver_predicate` must genuinely be absent from the
  resolver's declared predicate list

## Status vocabulary

| Status | Meaning |
|---|---|
| `present` | declared + authority + reachable |
| `present_unwired` | declared + authority implemented, not wired to runtime |
| `present_no_resolver_predicate` | declared + engine constructor; resolver config has no predicate |
| `present_constructor_unreachable` | declared; named blocking gap in the capability contract |
| `present_undefined` | identity slot exists; no definition |
| `absent` | no declaration, no authority — stated explicitly, never silently omitted |

## Coverage

**{cov['named_count']} / {cov['canonical_total']}** canonical features are named by at least one
concept record. The remainder are measured but not yet bridged to vocabulary — see
`feature_schema.bridge.md` §Coverage for the list. That gap is a **finding**, not a defect:
it is exactly the set of quantities the repository computes that no trading word in this
bridge's scope refers to.

## Scope limits

- Concepts in scope: {', '.join(c['concept'].split(' (')[0] for c in CONCEPTS)}.
- Not in scope: entry/exit rules, directional prediction, position sizing.
- This bridge grants **no** runtime authority, **no** promotion, and changes **no** engine
  behaviour. Promotion is a governance act (M4 QualificationGate → PromotionManager).
"""


# ----------------------------------- main -------------------------------------

def main(argv: list | None = None) -> int:
    ap = argparse.ArgumentParser(description="Generate the Bridge Layer specification.")
    ap.add_argument("--check", action="store_true",
                    help="validate only; write nothing (exit 1 on any problem)")
    ap.add_argument("--no-measure", action="store_true",
                    help="skip the FeaturePipeline dtype measurement (faster)")
    args = ap.parse_args(argv)

    schema = read_schema()
    ont = read_ontology()
    states = read_states()
    crt = read_crt_identity()
    resolver_states = read_resolver_states()
    git = git_facts()

    problems = validate(schema, ont, CONCEPTS, resolver_states)
    if problems:
        print("BRIDGE LAYER VALIDATION FAILED — nothing written:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    cov = coverage_report(schema)
    dt = {} if args.no_measure else measure_dtypes()

    print(f"bridge layer: {len(CONCEPTS)} concepts, {schema['dim']} canonical features, "
          f"{len(crt['states'])} CRT states, {len(crt['constructors'])} constructors")
    print(f"  coverage: {cov['named_count']}/{cov['canonical_total']} features named by a concept")
    print(f"  dtypes: {dt.get('source') or dt.get('error') or 'not measured'}")
    print(f"  commit: {git['commit'][:12]} on {git['branch']}")

    if args.check:
        print("validation OK (--check: no files written)")
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    written = []
    artifacts = {
        "README.md": render_readme(schema, crt, states, cov, git, dt),
        "CANONICAL_FEATURES.html": render_html(schema, ont, dt),
        "concepts.yaml": render_concepts_yaml(schema, cov, git),
        "feature_schema.bridge.md": render_feature_schema_bridge(schema, ont, cov),
        "state_ontology.md": render_state_ontology(states),
        "crt_engine_v2_concept_map.md": render_crt_concept_map(crt, resolver_states),
        "crt_state_resolver_bridge.md": render_resolver_bridge(crt, resolver_states),
    }
    for name, body in artifacts.items():
        (OUT / name).write_text(body, encoding="utf-8")
        written.append((name, len(body)))

    for name, n in written:
        print(f"  wrote bridge_layer/{name} ({n} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())



