"""
gen_crt_state_identity.py
==========================
Generates `src/config_layer/_crt_state_generated.py` from `active_models.yaml`, making the
ontology the single authored source for CRT state IDENTITY (the enum, the transition graph, and
the parent/execution partition). CH-crt-state-generation-v1, 2026-08-31.

Why active_models.yaml and NOT market_crt_states.yaml
------------------------------------------------------
`active_models.yaml:crt.runtime` is the surface already wired FAIL-CLOSED into production:
`crt_engine_v2.CRTEngine.__init__` calls `load_and_validate_state_contracts()` ->
`build_runtime_transition_graph_from_bundle()` and injects the result into `StateMachine`, with
`state_contract_loader._validate_transition_graph` demanding exact edge-set equality against the
code seed at every construction. `configs/formulas/market_crt_states.yaml` is the CRTStateResolver's
surface -- the implementation F-069 measured at 88.16% agreement with this engine. Generating from
the resolver's file would adopt the divergent side's declaration surface; generating from the
runtime's file does not.

What is generated, and what deliberately is not
------------------------------------------------
GENERATED (mechanical, no judgement):
    CRTState, VALID_TRANSITIONS, PARENT_TIMEFRAME_STATES, EXECUTION_TIMEFRAME_STATES
NOT GENERATED (stays hand-authored in state_identity.py):
    Direction, RejectReason      -- not declared in the ontology at all
    _VALID_KILL_PRECEDENCE       -- SEM-021 policy vocabulary, not state identity
    CRTConfig (53 fields)        -- configuration schema, a different concern entirely
    ALL RATIONALE PROSE          -- see "Comments" below

Comments / rationale are NOT moved into YAML
----------------------------------------------
The hand-authored definitions carry ~30 lines of governance rationale (why the parent sub-graph is
disjoint, the F-074 / CH-htfcrt-parent-candle-smc-v1 citations, why crt_executable_state_graph.json
must not grow to cover parent states). Mechanical generation would delete all of it, which would be
a real loss of meaning (CLAUDE.md 6.2 rule 4). It is therefore RETAINED VERBATIM in
`state_identity.py` alongside the re-exports -- the generated module holds bare definitions and
points back at it.

Per-state descriptions were considered for the ontology and REJECTED for a concrete reason: the
natural home (`crt.runtime.state_contracts`) is parsed by `state_contract.parse_state_contract`,
which is fail-closed on unknown fields AND requires every allowed field -- so adding a
`description:` there would raise at every `CRTEngine()` construction. A future home would have to
be a new sibling key, never that block.

Generated at BUILD time, committed -- never at import
------------------------------------------------------
`state_identity` is imported at module load across the codebase and `state_contract_loader` imports
it; reading YAML at import would add per-import I/O and risk a cycle. The artifact is committed and
`--check` compares regenerate-vs-committed.

What this does to the existing guards (stated plainly, not glossed)
--------------------------------------------------------------------
`tests/test_crt_state_invariants.py` (active_models.yaml <-> code) and the runtime
`_validate_transition_graph` become FRESHNESS checks on the generated artifact rather than
independent cross-record drift detectors, because both sides now derive from one file. That is a
real downgrade and is documented in those files too.

What still provides genuine independence:
  * `tests/test_crt_states_yaml_transition_parity.py` (SK-0) compares against
    `configs/formulas/market_crt_states.yaml` -- a DIFFERENT file that is NOT the generation
    source, so it remains a fully non-vacuous cross-file guard.
  * `tests/test_crt_states_yaml_state_names.py` (Phase F1) -- same, on the states[] axis.

Usage
    python scripts/maintenance/gen_crt_state_identity.py            # write the module
    python scripts/maintenance/gen_crt_state_identity.py --check    # exit 1 if committed is stale
"""
from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SOURCE_YAML = ROOT / "active_models.yaml"
OUT_PATH = ROOT / "src" / "config_layer" / "_crt_state_generated.py"

_HEADER = '''"""
_crt_state_generated.py -- GENERATED FILE, DO NOT EDIT BY HAND.

Generated by scripts/maintenance/gen_crt_state_identity.py from active_models.yaml
(crt.runtime.state_list / valid_transitions / parent_timeframe_states).

Re-exported by config_layer.state_identity, which is the module every consumer should import
from and which carries the governance rationale for these definitions. Nothing else should
import this module directly.

To change any of these: edit active_models.yaml, then re-run the generator. Editing this file
by hand is caught by `gen_crt_state_identity.py --check` and by
tests/test_crt_state_generated_parity.py.
"""
from __future__ import annotations

from enum import Enum, auto

__all__ = [
    "CRTState",
    "VALID_TRANSITIONS",
    "PARENT_TIMEFRAME_STATES",
    "EXECUTION_TIMEFRAME_STATES",
]


class CRTState(Enum):
    """Legal states in the CRT state machine.

    Members and their ORDER come from active_models.yaml crt.runtime.state_list. Order is
    load-bearing: values are `auto()` (1..N by declaration order) and reach user-visible
    strings via `.value`, so reordering state_list silently renumbers them. The full
    name->value map is pinned by tests/test_crt_state_generated_parity.py.
    """
'''


def _load_runtime() -> dict:
    # utf-8 forced: active_models.yaml carries box-drawing/math glyphs that break Windows cp1252.
    with io.open(SOURCE_YAML, encoding="utf-8") as fh:
        return yaml.safe_load(fh)["crt"]["runtime"]


def render() -> str:
    rt = _load_runtime()
    state_list: list[str] = list(rt["state_list"])
    transitions: dict[str, list[str]] = dict(rt["valid_transitions"])
    parent_states: list[str] = list(rt["parent_timeframe_states"])

    # ── Fail closed on any inconsistency in the SOURCE, before emitting anything ──
    declared_count = rt.get("states")
    if declared_count != len(state_list):
        raise SystemExit(
            f"active_models.yaml: crt.runtime.states={declared_count} but state_list has "
            f"{len(state_list)} entries"
        )
    if len(set(state_list)) != len(state_list):
        raise SystemExit(f"active_models.yaml: duplicate names in state_list: {state_list}")
    if set(transitions) != set(state_list):
        raise SystemExit(
            "active_models.yaml: valid_transitions keys != state_list "
            f"(only in transitions: {sorted(set(transitions) - set(state_list))}; "
            f"only in state_list: {sorted(set(state_list) - set(transitions))})"
        )
    unknown_targets = {
        t for targets in transitions.values() for t in targets if t not in set(state_list)
    }
    if unknown_targets:
        raise SystemExit(
            f"active_models.yaml: valid_transitions references undeclared states: "
            f"{sorted(unknown_targets)}"
        )
    unknown_parent = [s for s in parent_states if s not in set(state_list)]
    if unknown_parent:
        raise SystemExit(
            f"active_models.yaml: parent_timeframe_states names undeclared states: {unknown_parent}"
        )

    out = [_HEADER]
    width = max(len(s) for s in state_list)
    for name in state_list:
        out.append(f"    {name.ljust(width)} = auto()\n")

    out.append("\n\nVALID_TRANSITIONS: dict[CRTState, list[CRTState]] = {\n")
    key_width = max(len(s) for s in transitions) + len("CRTState.") + 1
    for src in state_list:  # emit in state_list order for a stable, reviewable diff
        targets = ", ".join(f"CRTState.{t}" for t in transitions[src])
        key = f"CRTState.{src}:"
        out.append(f"    {key.ljust(key_width)} [{targets}],\n")
    out.append("}\n")

    out.append("\n\nPARENT_TIMEFRAME_STATES: frozenset[CRTState] = frozenset({\n")
    for name in parent_states:
        out.append(f"    CRTState.{name},\n")
    out.append("})\n")
    out.append(
        "\n# Derived complement -- deliberately NOT declared in the ontology, so the split has\n"
        "# exactly one authored record (the parent list) and cannot self-disagree.\n"
        "EXECUTION_TIMEFRAME_STATES: frozenset[CRTState] = "
        "frozenset(CRTState) - PARENT_TIMEFRAME_STATES\n"
    )
    return "".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument(
        "--check", action="store_true",
        help="exit 1 if the committed file differs from a fresh render (CI / floor use)",
    )
    args = ap.parse_args(argv)

    rendered = render()

    if args.check:
        if not OUT_PATH.exists():
            print(f"MISSING: {OUT_PATH.relative_to(ROOT)} has not been generated", file=sys.stderr)
            return 1
        current = io.open(OUT_PATH, encoding="utf-8").read()
        if current != rendered:
            print(
                f"STALE: {OUT_PATH.relative_to(ROOT)} differs from a fresh render of "
                f"{SOURCE_YAML.name}.\nRe-run: python scripts/maintenance/gen_crt_state_identity.py",
                file=sys.stderr,
            )
            return 1
        print(f"--check OK: {OUT_PATH.relative_to(ROOT)} is current with {SOURCE_YAML.name}")
        return 0

    with io.open(OUT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(rendered)
    print(f"wrote {OUT_PATH.relative_to(ROOT)} from {SOURCE_YAML.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
