from pathlib import Path
p = Path("docs/governance/CANONICAL_LAYER_IDENTITY_CONTRACT.md")
t = p.read_text(encoding="utf-8")
if "backtest_g1g2_v2" in t:
    print("contract already has id")
else:
    needle = "| `none_gross` | Gross-only; must be named, never implied |"
    add = (
        needle
        + "\n| `backtest_g1g2_v2` | Production backtest G1+G2 ledger (REM-COST-04) |"
        + "\n| `backtest_zero_cost` | Reserve-only; never generated by backtest_v2 today |"
    )
    if needle not in t:
        raise SystemExit("needle missing: " + repr([ln for ln in t.splitlines() if "none_gross" in ln][:3]))
    p.write_text(t.replace(needle, add, 1), encoding="utf-8")
    print("contract patched")

# Drop REM-COST-04 from standing BLOCKER_OPEN list in resolver (implemented)
rp = Path("scripts/research/live_alert_resolver.py")
rt = rp.read_text(encoding="utf-8")
old = '''    for rid, msg in [
        ("REM-COST-04", "backtest_g1g2_v2 not in L5 COST_MODEL_IDS (governance)"),
        ("REM-SOFT-01", "Ultron gates gross RR; ledger nets G1+G2"),
        ("REM-CRT-02", "Need dual-write CRT feeder on live/paper rail for live chart colors"),
    ]:'''
new = '''    for rid, msg in [
        ("REM-SOFT-01", "Ultron gates gross RR; ledger nets G1+G2"),
        ("REM-CRT-02", "Paper side-car exists; streaming/orchestrator density still research-open"),
    ]:'''
if old not in rt:
    print("resolver block not found exact — check manually")
else:
    rp.write_text(rt.replace(old, new, 1), encoding="utf-8")
    print("resolver blockers updated")
